<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Preliminaries | Tool Shed for Applied Data Analytics with R</title>
  <meta name="description" content="Chapter 2 Preliminaries | Tool Shed for Applied Data Analytics with R" />
  <meta name="generator" content="bookdown 0.28 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Preliminaries | Tool Shed for Applied Data Analytics with R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://yaydede.github.io/ToolShed//png/cover2.png" />
  
  <meta name="github-repo" content="yaydede/ToolShed_draft" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Preliminaries | Tool Shed for Applied Data Analytics with R" />
  
  
  <meta name="twitter:image" content="https://yaydede.github.io/ToolShed//png/cover2.png" />

<meta name="author" content="Yigit Aydede" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intro.html"/>
<link rel="next" href="learning-systems.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.24/datatables.js"></script>
<link href="libs/dt-core-1.11.3/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.11.3/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.11.3/js/jquery.dataTables.min.js"></script>
<link href="libs/nouislider-7.0.10/jquery.nouislider.min.css" rel="stylesheet" />
<script src="libs/nouislider-7.0.10/jquery.nouislider.min.js"></script>
<link href="libs/selectize-0.12.0/selectize.bootstrap3.css" rel="stylesheet" />
<script src="libs/selectize-0.12.0/selectize.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Tool Shed</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#who"><i class="fa fa-check"></i>Who</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i>License</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> How we define Machine Learning</a></li>
<li class="chapter" data-level="2" data-path="preliminaries.html"><a href="preliminaries.html"><i class="fa fa-check"></i><b>2</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="2.1" data-path="preliminaries.html"><a href="preliminaries.html#data-and-dataset-types"><i class="fa fa-check"></i><b>2.1</b> Data and dataset types</a></li>
<li class="chapter" data-level="2.2" data-path="preliminaries.html"><a href="preliminaries.html#plots"><i class="fa fa-check"></i><b>2.2</b> Plots</a></li>
<li class="chapter" data-level="2.3" data-path="preliminaries.html"><a href="preliminaries.html#probability-distributions-with-r"><i class="fa fa-check"></i><b>2.3</b> Probability Distributions with R</a></li>
<li class="chapter" data-level="2.4" data-path="preliminaries.html"><a href="preliminaries.html#regressions"><i class="fa fa-check"></i><b>2.4</b> Regressions</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="preliminaries.html"><a href="preliminaries.html#ordinary-least-squares-ols"><i class="fa fa-check"></i><b>2.4.1</b> Ordinary Least Squares (OLS)</a></li>
<li class="chapter" data-level="2.4.2" data-path="preliminaries.html"><a href="preliminaries.html#maximum-likelihood-estimators"><i class="fa fa-check"></i><b>2.4.2</b> Maximum Likelihood Estimators</a></li>
<li class="chapter" data-level="2.4.3" data-path="preliminaries.html"><a href="preliminaries.html#estimating-mle-with-r"><i class="fa fa-check"></i><b>2.4.3</b> Estimating MLE with R</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="preliminaries.html"><a href="preliminaries.html#blue"><i class="fa fa-check"></i><b>2.5</b> BLUE</a></li>
<li class="chapter" data-level="2.6" data-path="preliminaries.html"><a href="preliminaries.html#modeling-the-data"><i class="fa fa-check"></i><b>2.6</b> Modeling the data</a></li>
<li class="chapter" data-level="2.7" data-path="preliminaries.html"><a href="preliminaries.html#causal-vs.-predictive-models"><i class="fa fa-check"></i><b>2.7</b> Causal vs. Predictive Models</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="preliminaries.html"><a href="preliminaries.html#causal-models"><i class="fa fa-check"></i><b>2.7.1</b> Causal Models</a></li>
<li class="chapter" data-level="2.7.2" data-path="preliminaries.html"><a href="preliminaries.html#prediction-models"><i class="fa fa-check"></i><b>2.7.2</b> Prediction Models</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="preliminaries.html"><a href="preliminaries.html#simulation"><i class="fa fa-check"></i><b>2.8</b> Simulation</a></li>
</ul></li>
<li class="part"><span><b>I Formal Look at Prediction</b></span></li>
<li class="chapter" data-level="" data-path="learning-systems.html"><a href="learning-systems.html"><i class="fa fa-check"></i>Learning Systems</a></li>
<li class="chapter" data-level="3" data-path="bias-variance-tradeoff.html"><a href="bias-variance-tradeoff.html"><i class="fa fa-check"></i><b>3</b> Bias-Variance Tradeoff</a>
<ul>
<li class="chapter" data-level="3.1" data-path="bias-variance-tradeoff.html"><a href="bias-variance-tradeoff.html#estimator-and-mse"><i class="fa fa-check"></i><b>3.1</b> Estimator and MSE</a></li>
<li class="chapter" data-level="3.2" data-path="bias-variance-tradeoff.html"><a href="bias-variance-tradeoff.html#prediction---mspe"><i class="fa fa-check"></i><b>3.2</b> Prediction - MSPE</a></li>
<li class="chapter" data-level="3.3" data-path="bias-variance-tradeoff.html"><a href="bias-variance-tradeoff.html#biased-estimator-as-a-predictor"><i class="fa fa-check"></i><b>3.3</b> Biased estimator as a predictor</a></li>
<li class="chapter" data-level="3.4" data-path="bias-variance-tradeoff.html"><a href="bias-variance-tradeoff.html#dropping-a-variable-in-a-regression"><i class="fa fa-check"></i><b>3.4</b> Dropping a variable in a regression</a></li>
<li class="chapter" data-level="3.5" data-path="bias-variance-tradeoff.html"><a href="bias-variance-tradeoff.html#uncertainty-in-estimations-and-predictions"><i class="fa fa-check"></i><b>3.5</b> Uncertainty in estimations and predictions</a></li>
<li class="chapter" data-level="3.6" data-path="bias-variance-tradeoff.html"><a href="bias-variance-tradeoff.html#prediction-interval-for-unbiased-ols-predictor"><i class="fa fa-check"></i><b>3.6</b> Prediction interval for unbiased OLS predictor</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="overfitting.html"><a href="overfitting.html"><i class="fa fa-check"></i><b>4</b> Overfitting</a></li>
<li class="part"><span><b>II Nonparametric Estimations</b></span></li>
<li class="chapter" data-level="" data-path="parametric-vs.html"><a href="parametric-vs.html"><i class="fa fa-check"></i>Parametric vs. Nonparametric methods</a></li>
<li class="chapter" data-level="5" data-path="parametric-estimations.html"><a href="parametric-estimations.html"><i class="fa fa-check"></i><b>5</b> Parametric Estimations</a>
<ul>
<li class="chapter" data-level="5.1" data-path="parametric-estimations.html"><a href="parametric-estimations.html#linear-probability-models-lpm"><i class="fa fa-check"></i><b>5.1</b> Linear Probability Models (LPM)</a></li>
<li class="chapter" data-level="5.2" data-path="parametric-estimations.html"><a href="parametric-estimations.html#logistic-regression"><i class="fa fa-check"></i><b>5.2</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="parametric-estimations.html"><a href="parametric-estimations.html#estimating-logistic-regression"><i class="fa fa-check"></i><b>5.2.1</b> Estimating Logistic Regression</a></li>
<li class="chapter" data-level="5.2.2" data-path="parametric-estimations.html"><a href="parametric-estimations.html#cost-functions"><i class="fa fa-check"></i><b>5.2.2</b> Cost functions</a></li>
<li class="chapter" data-level="5.2.3" data-path="parametric-estimations.html"><a href="parametric-estimations.html#deviance"><i class="fa fa-check"></i><b>5.2.3</b> Deviance</a></li>
<li class="chapter" data-level="5.2.4" data-path="parametric-estimations.html"><a href="parametric-estimations.html#predictive-accuracy"><i class="fa fa-check"></i><b>5.2.4</b> Predictive accuracy</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="nonparametric-estimations---basics.html"><a href="nonparametric-estimations---basics.html"><i class="fa fa-check"></i><b>6</b> Nonparametric Estimations - Basics</a>
<ul>
<li class="chapter" data-level="6.1" data-path="nonparametric-estimations---basics.html"><a href="nonparametric-estimations---basics.html#density-estimations"><i class="fa fa-check"></i><b>6.1</b> Density Estimations</a></li>
<li class="chapter" data-level="6.2" data-path="nonparametric-estimations---basics.html"><a href="nonparametric-estimations---basics.html#kernel-regressions"><i class="fa fa-check"></i><b>6.2</b> Kernel regressions</a></li>
<li class="chapter" data-level="6.3" data-path="nonparametric-estimations---basics.html"><a href="nonparametric-estimations---basics.html#regression-splines"><i class="fa fa-check"></i><b>6.3</b> Regression Splines</a></li>
<li class="chapter" data-level="6.4" data-path="nonparametric-estimations---basics.html"><a href="nonparametric-estimations---basics.html#mars---multivariate-adaptive-regression-splines"><i class="fa fa-check"></i><b>6.4</b> MARS - Multivariate Adaptive Regression Splines</a></li>
<li class="chapter" data-level="6.5" data-path="nonparametric-estimations---basics.html"><a href="nonparametric-estimations---basics.html#gam---generalized-additive-model"><i class="fa fa-check"></i><b>6.5</b> GAM - Generalized Additive Model</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="smoothing.html"><a href="smoothing.html"><i class="fa fa-check"></i><b>7</b> Smoothing</a>
<ul>
<li class="chapter" data-level="7.1" data-path="smoothing.html"><a href="smoothing.html#using-bins"><i class="fa fa-check"></i><b>7.1</b> Using bins</a></li>
<li class="chapter" data-level="7.2" data-path="smoothing.html"><a href="smoothing.html#kernel-smoothing"><i class="fa fa-check"></i><b>7.2</b> Kernel smoothing</a></li>
<li class="chapter" data-level="7.3" data-path="smoothing.html"><a href="smoothing.html#locally-weighted-regression-loess"><i class="fa fa-check"></i><b>7.3</b> Locally weighted regression <code>loess()</code></a></li>
<li class="chapter" data-level="7.4" data-path="smoothing.html"><a href="smoothing.html#smooth-spline-regression"><i class="fa fa-check"></i><b>7.4</b> Smooth Spline Regression</a></li>
<li class="chapter" data-level="7.5" data-path="smoothing.html"><a href="smoothing.html#multivariate-loess"><i class="fa fa-check"></i><b>7.5</b> Multivariate Loess</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="nonparametric-classifier---knn.html"><a href="nonparametric-classifier---knn.html"><i class="fa fa-check"></i><b>8</b> Nonparametric Classifier - kNN</a>
<ul>
<li class="chapter" data-level="8.1" data-path="nonparametric-classifier---knn.html"><a href="nonparametric-classifier---knn.html#mnist-dataset"><i class="fa fa-check"></i><b>8.1</b> <code>mnist</code> Dataset</a></li>
<li class="chapter" data-level="8.2" data-path="nonparametric-classifier---knn.html"><a href="nonparametric-classifier---knn.html#linear-classifiers-again"><i class="fa fa-check"></i><b>8.2</b> Linear classifiers (again)</a></li>
<li class="chapter" data-level="8.3" data-path="nonparametric-classifier---knn.html"><a href="nonparametric-classifier---knn.html#k-nearest-neighbors"><i class="fa fa-check"></i><b>8.3</b> k-Nearest Neighbors</a></li>
<li class="chapter" data-level="8.4" data-path="nonparametric-classifier---knn.html"><a href="nonparametric-classifier---knn.html#knn-with-caret"><i class="fa fa-check"></i><b>8.4</b> kNN with caret</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="nonparametric-classifier---knn.html"><a href="nonparametric-classifier---knn.html#mnist_27"><i class="fa fa-check"></i><b>8.4.1</b> <code>mnist_27</code></a></li>
<li class="chapter" data-level="8.4.2" data-path="nonparametric-classifier---knn.html"><a href="nonparametric-classifier---knn.html#adult-dataset"><i class="fa fa-check"></i><b>8.4.2</b> Adult dataset</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>III Self-Learning</b></span></li>
<li class="chapter" data-level="9" data-path="hyperparameter-tuning.html"><a href="hyperparameter-tuning.html"><i class="fa fa-check"></i><b>9</b> Hyperparameter Tuning</a>
<ul>
<li class="chapter" data-level="9.1" data-path="hyperparameter-tuning.html"><a href="hyperparameter-tuning.html#training-validation-and-test-datasets"><i class="fa fa-check"></i><b>9.1</b> Training, validation, and test datasets</a></li>
<li class="chapter" data-level="9.2" data-path="hyperparameter-tuning.html"><a href="hyperparameter-tuning.html#splitting-the-data-randomly"><i class="fa fa-check"></i><b>9.2</b> Splitting the data randomly</a></li>
<li class="chapter" data-level="9.3" data-path="hyperparameter-tuning.html"><a href="hyperparameter-tuning.html#k-fold-cross-validation"><i class="fa fa-check"></i><b>9.3</b> k-fold cross validation</a></li>
<li class="chapter" data-level="9.4" data-path="hyperparameter-tuning.html"><a href="hyperparameter-tuning.html#grid-search"><i class="fa fa-check"></i><b>9.4</b> Grid search</a></li>
<li class="chapter" data-level="9.5" data-path="hyperparameter-tuning.html"><a href="hyperparameter-tuning.html#cross-validated-grid-search"><i class="fa fa-check"></i><b>9.5</b> Cross-validated grid search</a></li>
<li class="chapter" data-level="9.6" data-path="hyperparameter-tuning.html"><a href="hyperparameter-tuning.html#when-the-data-is-time-series"><i class="fa fa-check"></i><b>9.6</b> When the data is time-series</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="tuning-in-classification.html"><a href="tuning-in-classification.html"><i class="fa fa-check"></i><b>10</b> Tuning in Classification</a>
<ul>
<li class="chapter" data-level="10.1" data-path="tuning-in-classification.html"><a href="tuning-in-classification.html#confusion-matrix"><i class="fa fa-check"></i><b>10.1</b> Confusion matrix</a></li>
<li class="chapter" data-level="10.2" data-path="tuning-in-classification.html"><a href="tuning-in-classification.html#performance-measures"><i class="fa fa-check"></i><b>10.2</b> Performance measures</a></li>
<li class="chapter" data-level="10.3" data-path="tuning-in-classification.html"><a href="tuning-in-classification.html#roc---reciever-operating-curve"><i class="fa fa-check"></i><b>10.3</b> ROC - Reciever Operating Curve</a></li>
<li class="chapter" data-level="10.4" data-path="tuning-in-classification.html"><a href="tuning-in-classification.html#auc---area-under-the-curve"><i class="fa fa-check"></i><b>10.4</b> AUC - Area Under the Curve</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="classification-example.html"><a href="classification-example.html"><i class="fa fa-check"></i><b>11</b> Classification Example</a>
<ul>
<li class="chapter" data-level="11.1" data-path="classification-example.html"><a href="classification-example.html#lpm"><i class="fa fa-check"></i><b>11.1</b> LPM</a></li>
<li class="chapter" data-level="11.2" data-path="classification-example.html"><a href="classification-example.html#logistic-regression-1"><i class="fa fa-check"></i><b>11.2</b> Logistic Regression</a></li>
<li class="chapter" data-level="11.3" data-path="classification-example.html"><a href="classification-example.html#knn"><i class="fa fa-check"></i><b>11.3</b> kNN</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="classification-example.html"><a href="classification-example.html#knn-10-fold-cv"><i class="fa fa-check"></i><b>11.3.1</b> kNN 10-fold CV</a></li>
<li class="chapter" data-level="11.3.2" data-path="classification-example.html"><a href="classification-example.html#knn-with-caret-1"><i class="fa fa-check"></i><b>11.3.2</b> kNN with <code>caret</code></a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Tree-based Models</b></span></li>
<li class="chapter" data-level="12" data-path="cart.html"><a href="cart.html"><i class="fa fa-check"></i><b>12</b> CART</a>
<ul>
<li class="chapter" data-level="12.1" data-path="cart.html"><a href="cart.html#cart---classification-tree"><i class="fa fa-check"></i><b>12.1</b> CART - Classification Tree</a></li>
<li class="chapter" data-level="12.2" data-path="cart.html"><a href="cart.html#rpart---recursive-partitioning"><i class="fa fa-check"></i><b>12.2</b> <code>rpart()</code> - Recursive Partitioning</a></li>
<li class="chapter" data-level="12.3" data-path="cart.html"><a href="cart.html#pruning"><i class="fa fa-check"></i><b>12.3</b> Pruning</a></li>
<li class="chapter" data-level="12.4" data-path="cart.html"><a href="cart.html#classification-with-titanic"><i class="fa fa-check"></i><b>12.4</b> Classification with Titanic</a></li>
<li class="chapter" data-level="12.5" data-path="cart.html"><a href="cart.html#regression-tree"><i class="fa fa-check"></i><b>12.5</b> Regression Tree</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="ensemble-learning.html"><a href="ensemble-learning.html"><i class="fa fa-check"></i><b>13</b> Ensemble learning</a>
<ul>
<li class="chapter" data-level="13.1" data-path="ensemble-learning.html"><a href="ensemble-learning.html#bagging"><i class="fa fa-check"></i><b>13.1</b> Bagging</a></li>
<li class="chapter" data-level="13.2" data-path="ensemble-learning.html"><a href="ensemble-learning.html#random-forest"><i class="fa fa-check"></i><b>13.2</b> Random Forest</a></li>
<li class="chapter" data-level="13.3" data-path="ensemble-learning.html"><a href="ensemble-learning.html#boosting"><i class="fa fa-check"></i><b>13.3</b> Boosting</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="ensemble-learning.html"><a href="ensemble-learning.html#sequential-ensemble-with-gbm"><i class="fa fa-check"></i><b>13.3.1</b> Sequential ensemble with <code>gbm</code></a></li>
<li class="chapter" data-level="13.3.2" data-path="ensemble-learning.html"><a href="ensemble-learning.html#adaboost"><i class="fa fa-check"></i><b>13.3.2</b> AdaBoost</a></li>
<li class="chapter" data-level="13.3.3" data-path="ensemble-learning.html"><a href="ensemble-learning.html#extreme-gradient-boosting-xgboost"><i class="fa fa-check"></i><b>13.3.3</b> Extreme Gradient Boosting (XGBoost)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="ensemble-applications.html"><a href="ensemble-applications.html"><i class="fa fa-check"></i><b>14</b> Ensemble Applications</a>
<ul>
<li class="chapter" data-level="14.1" data-path="ensemble-applications.html"><a href="ensemble-applications.html#classification"><i class="fa fa-check"></i><b>14.1</b> Classification</a></li>
<li class="chapter" data-level="14.2" data-path="ensemble-applications.html"><a href="ensemble-applications.html#regression"><i class="fa fa-check"></i><b>14.2</b> Regression</a></li>
<li class="chapter" data-level="14.3" data-path="ensemble-applications.html"><a href="ensemble-applications.html#dataset-level-explainers"><i class="fa fa-check"></i><b>14.3</b> Dataset-level explainers</a></li>
<li class="chapter" data-level="14.4" data-path="ensemble-applications.html"><a href="ensemble-applications.html#boosting-applications"><i class="fa fa-check"></i><b>14.4</b> Boosting Applications</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="ensemble-applications.html"><a href="ensemble-applications.html#regression-1"><i class="fa fa-check"></i><b>14.4.1</b> Regression</a></li>
<li class="chapter" data-level="14.4.2" data-path="ensemble-applications.html"><a href="ensemble-applications.html#random-search-with-parallel-processing"><i class="fa fa-check"></i><b>14.4.2</b> Random search with parallel processing</a></li>
<li class="chapter" data-level="14.4.3" data-path="ensemble-applications.html"><a href="ensemble-applications.html#boosting-vs.-others"><i class="fa fa-check"></i><b>14.4.3</b> Boosting vs. Others</a></li>
<li class="chapter" data-level="14.4.4" data-path="ensemble-applications.html"><a href="ensemble-applications.html#classification-1"><i class="fa fa-check"></i><b>14.4.4</b> Classification</a></li>
<li class="chapter" data-level="14.4.5" data-path="ensemble-applications.html"><a href="ensemble-applications.html#adaboost.m1"><i class="fa fa-check"></i><b>14.4.5</b> AdaBoost.M1</a></li>
<li class="chapter" data-level="14.4.6" data-path="ensemble-applications.html"><a href="ensemble-applications.html#classification-with-xgboost"><i class="fa fa-check"></i><b>14.4.6</b> Classification with XGBoost</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>V SVM &amp; Neural Networks</b></span></li>
<li class="chapter" data-level="15" data-path="support-vector-machines.html"><a href="support-vector-machines.html"><i class="fa fa-check"></i><b>15</b> Support Vector Machines</a>
<ul>
<li class="chapter" data-level="15.1" data-path="support-vector-machines.html"><a href="support-vector-machines.html#optimal-separating-classifier"><i class="fa fa-check"></i><b>15.1</b> Optimal Separating Classifier</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="support-vector-machines.html"><a href="support-vector-machines.html#the-margin"><i class="fa fa-check"></i><b>15.1.1</b> The Margin</a></li>
<li class="chapter" data-level="15.1.2" data-path="support-vector-machines.html"><a href="support-vector-machines.html#the-non-separable-case"><i class="fa fa-check"></i><b>15.1.2</b> The Non-Separable Case</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="support-vector-machines.html"><a href="support-vector-machines.html#nonlinear-boundary-with-kernels"><i class="fa fa-check"></i><b>15.2</b> Nonlinear Boundary with Kernels</a></li>
<li class="chapter" data-level="15.3" data-path="support-vector-machines.html"><a href="support-vector-machines.html#application-with-svm"><i class="fa fa-check"></i><b>15.3</b> Application with SVM</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="neural-networks.html"><a href="neural-networks.html"><i class="fa fa-check"></i><b>16</b> Neural Networks</a></li>
<li class="part"><span><b>VI Penalized Regressions</b></span></li>
<li class="chapter" data-level="" data-path="parametric-models-in-prediction.html"><a href="parametric-models-in-prediction.html"><i class="fa fa-check"></i>Parametric models in prediction</a></li>
<li class="chapter" data-level="17" data-path="ridge.html"><a href="ridge.html"><i class="fa fa-check"></i><b>17</b> Ridge</a></li>
<li class="chapter" data-level="18" data-path="lasso.html"><a href="lasso.html"><i class="fa fa-check"></i><b>18</b> Lasso</a>
<ul>
<li class="chapter" data-level="18.1" data-path="lasso.html"><a href="lasso.html#regression-2"><i class="fa fa-check"></i><b>18.1</b> Regression</a></li>
<li class="chapter" data-level="18.2" data-path="lasso.html"><a href="lasso.html#lpmlogistic"><i class="fa fa-check"></i><b>18.2</b> LPM/Logistic</a></li>
<li class="chapter" data-level="18.3" data-path="lasso.html"><a href="lasso.html#adaptive-lasso"><i class="fa fa-check"></i><b>18.3</b> Adaptive Lasso</a></li>
<li class="chapter" data-level="18.4" data-path="lasso.html"><a href="lasso.html#elasticnet"><i class="fa fa-check"></i><b>18.4</b> ElasticNet</a></li>
</ul></li>
<li class="part"><span><b>VII Causality and Machine Learning</b></span></li>
<li class="chapter" data-level="19" data-path="model-selection.html"><a href="model-selection.html"><i class="fa fa-check"></i><b>19</b> Model Selection</a></li>
<li class="chapter" data-level="20" data-path="sparsity.html"><a href="sparsity.html"><i class="fa fa-check"></i><b>20</b> Sparsity</a></li>
<li class="chapter" data-level="21" data-path="use-of-machine-learning-in-causality.html"><a href="use-of-machine-learning-in-causality.html"><i class="fa fa-check"></i><b>21</b> Use of Machine Learning in Causality</a></li>
<li class="part"><span><b>VIII Dimension Reduction Methods</b></span></li>
<li class="chapter" data-level="" data-path="matrix-decompositions.html"><a href="matrix-decompositions.html"><i class="fa fa-check"></i>Matrix Decompositions</a></li>
<li class="chapter" data-level="22" data-path="eigenvectors-and-eigenvalues.html"><a href="eigenvectors-and-eigenvalues.html"><i class="fa fa-check"></i><b>22</b> Eigenvectors and eigenvalues</a></li>
<li class="chapter" data-level="23" data-path="singular-value-decomposition.html"><a href="singular-value-decomposition.html"><i class="fa fa-check"></i><b>23</b> Singular Value Decomposition</a></li>
<li class="chapter" data-level="24" data-path="rankr-approximations.html"><a href="rankr-approximations.html"><i class="fa fa-check"></i><b>24</b> Rank(r) Approximations</a></li>
<li class="chapter" data-level="25" data-path="moore-penrose-inverse.html"><a href="moore-penrose-inverse.html"><i class="fa fa-check"></i><b>25</b> Moore-Penrose inverse</a></li>
<li class="chapter" data-level="26" data-path="principle-component-analysis.html"><a href="principle-component-analysis.html"><i class="fa fa-check"></i><b>26</b> Principle Component Analysis</a></li>
<li class="chapter" data-level="27" data-path="factor-analysis.html"><a href="factor-analysis.html"><i class="fa fa-check"></i><b>27</b> Factor Analysis</a></li>
<li class="chapter" data-level="28" data-path="dynamic-mode-decomposition.html"><a href="dynamic-mode-decomposition.html"><i class="fa fa-check"></i><b>28</b> Dynamic Mode Decomposition</a></li>
<li class="part"><span><b>IX Time Series</b></span></li>
<li class="chapter" data-level="29" data-path="arima-models.html"><a href="arima-models.html"><i class="fa fa-check"></i><b>29</b> ARIMA models</a></li>
<li class="chapter" data-level="30" data-path="grid-search-for-arima.html"><a href="grid-search-for-arima.html"><i class="fa fa-check"></i><b>30</b> Grid search for ARIMA</a></li>
<li class="chapter" data-level="31" data-path="embedding.html"><a href="embedding.html"><i class="fa fa-check"></i><b>31</b> Embedding</a></li>
<li class="chapter" data-level="32" data-path="random-forest-1.html"><a href="random-forest-1.html"><i class="fa fa-check"></i><b>32</b> Random Forest</a></li>
<li class="chapter" data-level="33" data-path="neural-networks-1.html"><a href="neural-networks-1.html"><i class="fa fa-check"></i><b>33</b> Neural Networks</a></li>
<li class="part"><span><b>X Network Analysis</b></span></li>
<li class="chapter" data-level="" data-path="graphical-network-analysis.html"><a href="graphical-network-analysis.html"><i class="fa fa-check"></i>Graphical Network Analysis</a></li>
<li class="chapter" data-level="34" data-path="fundementals.html"><a href="fundementals.html"><i class="fa fa-check"></i><b>34</b> Fundementals</a>
<ul>
<li class="chapter" data-level="34.1" data-path="fundementals.html"><a href="fundementals.html#covariance"><i class="fa fa-check"></i><b>34.1</b> Covariance</a></li>
<li class="chapter" data-level="34.2" data-path="fundementals.html"><a href="fundementals.html#correlation"><i class="fa fa-check"></i><b>34.2</b> Correlation</a></li>
<li class="chapter" data-level="34.3" data-path="fundementals.html"><a href="fundementals.html#precision-matrix"><i class="fa fa-check"></i><b>34.3</b> Precision matrix</a></li>
<li class="chapter" data-level="34.4" data-path="fundementals.html"><a href="fundementals.html#semi-partial-correlation"><i class="fa fa-check"></i><b>34.4</b> Semi-partial correlation</a></li>
</ul></li>
<li class="chapter" data-level="35" data-path="regularized-covariance-matrix.html"><a href="regularized-covariance-matrix.html"><i class="fa fa-check"></i><b>35</b> Regularized covariance matrix</a>
<ul>
<li class="chapter" data-level="35.1" data-path="regularized-covariance-matrix.html"><a href="regularized-covariance-matrix.html#mle"><i class="fa fa-check"></i><b>35.1</b> MLE</a></li>
<li class="chapter" data-level="35.2" data-path="regularized-covariance-matrix.html"><a href="regularized-covariance-matrix.html#high-dimensional-data"><i class="fa fa-check"></i><b>35.2</b> High-dimensional data</a></li>
<li class="chapter" data-level="35.3" data-path="regularized-covariance-matrix.html"><a href="regularized-covariance-matrix.html#ridge-ell_2-and-glasso-ell_1"><i class="fa fa-check"></i><b>35.3</b> Ridge (<span class="math inline">\(\ell_{2}\)</span>) and glasso (<span class="math inline">\(\ell_{1}\)</span>)</a></li>
<li class="chapter" data-level="35.4" data-path="regularized-covariance-matrix.html"><a href="regularized-covariance-matrix.html#whats-graphical---graphical-ridge-or-glasso"><i class="fa fa-check"></i><b>35.4</b> What’s graphical - graphical ridge or glasso?</a></li>
</ul></li>
<li class="part"><span><b>XI Labs</b></span></li>
<li class="chapter" data-level="36" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html"><i class="fa fa-check"></i><b>36</b> R Lab 1 - Basics I</a>
<ul>
<li class="chapter" data-level="36.1" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#r-rstudio-and-r-packages"><i class="fa fa-check"></i><b>36.1</b> R, RStudio, and R Packages</a></li>
<li class="chapter" data-level="36.2" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#rstudio"><i class="fa fa-check"></i><b>36.2</b> RStudio</a></li>
<li class="chapter" data-level="36.3" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#working-directory"><i class="fa fa-check"></i><b>36.3</b> Working directory</a></li>
<li class="chapter" data-level="36.4" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#data-types-and-stuctures"><i class="fa fa-check"></i><b>36.4</b> Data Types and Stuctures</a></li>
<li class="chapter" data-level="36.5" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#vectors"><i class="fa fa-check"></i><b>36.5</b> Vectors</a></li>
<li class="chapter" data-level="36.6" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#subsetting-vectors"><i class="fa fa-check"></i><b>36.6</b> Subsetting Vectors</a></li>
<li class="chapter" data-level="36.7" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#vectorization-or-vector-operations"><i class="fa fa-check"></i><b>36.7</b> Vectorization or vector operations</a></li>
<li class="chapter" data-level="36.8" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#matrices"><i class="fa fa-check"></i><b>36.8</b> Matrices</a></li>
<li class="chapter" data-level="36.9" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#matrix-operations"><i class="fa fa-check"></i><b>36.9</b> Matrix Operations</a></li>
<li class="chapter" data-level="36.10" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#subsetting-matrix"><i class="fa fa-check"></i><b>36.10</b> Subsetting Matrix</a></li>
<li class="chapter" data-level="36.11" data-path="r-lab-1---basics-i.html"><a href="r-lab-1---basics-i.html#r-style-guide"><i class="fa fa-check"></i><b>36.11</b> R-Style Guide</a></li>
</ul></li>
<li class="chapter" data-level="37" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html"><i class="fa fa-check"></i><b>37</b> R Lab 2 - Basics II</a>
<ul>
<li class="chapter" data-level="37.1" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#data-frames-and-lists"><i class="fa fa-check"></i><b>37.1</b> Data frames and lists</a>
<ul>
<li class="chapter" data-level="37.1.1" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#lists"><i class="fa fa-check"></i><b>37.1.1</b> Lists</a></li>
<li class="chapter" data-level="37.1.2" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#data-frames"><i class="fa fa-check"></i><b>37.1.2</b> Data Frames</a></li>
<li class="chapter" data-level="37.1.3" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#reading-importing-and-writting-exporting-data-files"><i class="fa fa-check"></i><b>37.1.3</b> Reading (importing) and writting (exporting) data files</a></li>
<li class="chapter" data-level="37.1.4" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#subsetting-data-frames"><i class="fa fa-check"></i><b>37.1.4</b> Subsetting Data Frames</a></li>
<li class="chapter" data-level="37.1.5" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#plotting-from-data-frame"><i class="fa fa-check"></i><b>37.1.5</b> Plotting from data frame</a></li>
<li class="chapter" data-level="37.1.6" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#some-useful-functions"><i class="fa fa-check"></i><b>37.1.6</b> Some useful functions</a></li>
<li class="chapter" data-level="37.1.7" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#categorical-variables-in-data-frames"><i class="fa fa-check"></i><b>37.1.7</b> Categorical Variables in Data Frames</a></li>
</ul></li>
<li class="chapter" data-level="37.2" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#programming-basics"><i class="fa fa-check"></i><b>37.2</b> Programming Basics</a>
<ul>
<li class="chapter" data-level="37.2.1" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#ifelse"><i class="fa fa-check"></i><b>37.2.1</b> if/Else</a></li>
<li class="chapter" data-level="37.2.2" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#loops"><i class="fa fa-check"></i><b>37.2.2</b> Loops</a></li>
<li class="chapter" data-level="37.2.3" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#the-apply-family"><i class="fa fa-check"></i><b>37.2.3</b> The <code>apply()</code> family</a></li>
<li class="chapter" data-level="37.2.4" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#functions"><i class="fa fa-check"></i><b>37.2.4</b> Functions</a></li>
<li class="chapter" data-level="37.2.5" data-path="r-lab-2---basics-ii.html"><a href="r-lab-2---basics-ii.html#dplyr"><i class="fa fa-check"></i><b>37.2.5</b> <code>dplyr()</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="38" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html"><i class="fa fa-check"></i><b>38</b> R Lab 3 - Preparing the data</a>
<ul>
<li class="chapter" data-level="38.1" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html#preparing-the-data-for-a-regression-analysis-with-lm"><i class="fa fa-check"></i><b>38.1</b> Preparing the data for a regression analysis with <code>lm()</code></a>
<ul>
<li class="chapter" data-level="38.1.1" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html#factor-variables"><i class="fa fa-check"></i><b>38.1.1</b> Factor variables</a></li>
<li class="chapter" data-level="38.1.2" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html#dummy-coding"><i class="fa fa-check"></i><b>38.1.2</b> Dummy Coding</a></li>
<li class="chapter" data-level="38.1.3" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html#column-variable-names"><i class="fa fa-check"></i><b>38.1.3</b> Column (Variable) names</a></li>
<li class="chapter" data-level="38.1.4" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html#data-subsetting-and-missing-values"><i class="fa fa-check"></i><b>38.1.4</b> Data subsetting and missing values</a></li>
</ul></li>
<li class="chapter" data-level="38.2" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html#dummy-variable-models"><i class="fa fa-check"></i><b>38.2</b> “DUMMY” variable models</a>
<ul>
<li class="chapter" data-level="38.2.1" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html#mtcars-example"><i class="fa fa-check"></i><b>38.2.1</b> <code>mtcars</code> example</a></li>
<li class="chapter" data-level="38.2.2" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html#model.matrix"><i class="fa fa-check"></i><b>38.2.2</b> <code>model.matrix()</code></a></li>
<li class="chapter" data-level="38.2.3" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html#example-with-a-bigger-data-set-autompg"><i class="fa fa-check"></i><b>38.2.3</b> Example with a bigger data set: <code>Autompg</code></a></li>
<li class="chapter" data-level="38.2.4" data-path="r-lab-3---preparing-the-data.html"><a href="r-lab-3---preparing-the-data.html#some-more-data-management-tools-for-subsetting-complete.cases-is.na-and-within"><i class="fa fa-check"></i><b>38.2.4</b> Some more data management tools for subsetting: <code>complete.cases()</code>, <code>is.na()</code>, and <code>within()</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="39" data-path="r-lab-4---simulation-in-r.html"><a href="r-lab-4---simulation-in-r.html"><i class="fa fa-check"></i><b>39</b> R Lab 4 - Simulation in R</a>
<ul>
<li class="chapter" data-level="39.1" data-path="r-lab-4---simulation-in-r.html"><a href="r-lab-4---simulation-in-r.html#sampling-in-r-sample"><i class="fa fa-check"></i><b>39.1</b> Sampling in R: <code>sample()</code></a></li>
<li class="chapter" data-level="39.2" data-path="r-lab-4---simulation-in-r.html"><a href="r-lab-4---simulation-in-r.html#random-number-generating-with-probablity-distributions"><i class="fa fa-check"></i><b>39.2</b> Random number generating with probablity distributions</a></li>
<li class="chapter" data-level="39.3" data-path="r-lab-4---simulation-in-r.html"><a href="r-lab-4---simulation-in-r.html#simulation-for-statistical-inference"><i class="fa fa-check"></i><b>39.3</b> Simulation for statistical inference</a></li>
<li class="chapter" data-level="39.4" data-path="r-lab-4---simulation-in-r.html"><a href="r-lab-4---simulation-in-r.html#creataing-data-with-a-data-generating-model-dgm"><i class="fa fa-check"></i><b>39.4</b> Creataing data with a Data Generating Model (DGM)</a></li>
<li class="chapter" data-level="39.5" data-path="r-lab-4---simulation-in-r.html"><a href="r-lab-4---simulation-in-r.html#bootstrapping"><i class="fa fa-check"></i><b>39.5</b> Bootstrapping</a></li>
<li class="chapter" data-level="39.6" data-path="r-lab-4---simulation-in-r.html"><a href="r-lab-4---simulation-in-r.html#monty-hall---fun-example"><i class="fa fa-check"></i><b>39.6</b> Monty Hall - Fun example</a></li>
</ul></li>
<li class="part"><span><b>XII Appendix</b></span></li>
<li class="chapter" data-level="40" data-path="algorithmic-optimization.html"><a href="algorithmic-optimization.html"><i class="fa fa-check"></i><b>40</b> Algorithmic Optimization</a>
<ul>
<li class="chapter" data-level="40.1" data-path="algorithmic-optimization.html"><a href="algorithmic-optimization.html#brute-force-optimization"><i class="fa fa-check"></i><b>40.1</b> Brute-force optimization</a></li>
<li class="chapter" data-level="40.2" data-path="algorithmic-optimization.html"><a href="algorithmic-optimization.html#derivative-based-methods"><i class="fa fa-check"></i><b>40.2</b> Derivative-based methods</a></li>
<li class="chapter" data-level="40.3" data-path="algorithmic-optimization.html"><a href="algorithmic-optimization.html#gradient-descent"><i class="fa fa-check"></i><b>40.3</b> Gradient Descent</a>
<ul>
<li class="chapter" data-level="40.3.1" data-path="algorithmic-optimization.html"><a href="algorithmic-optimization.html#one-variable"><i class="fa fa-check"></i><b>40.3.1</b> One-variable</a></li>
<li class="chapter" data-level="40.3.2" data-path="algorithmic-optimization.html"><a href="algorithmic-optimization.html#multivariable"><i class="fa fa-check"></i><b>40.3.2</b> Multivariable</a></li>
</ul></li>
<li class="chapter" data-level="40.4" data-path="algorithmic-optimization.html"><a href="algorithmic-optimization.html#optimization-with-r"><i class="fa fa-check"></i><b>40.4</b> Optimization with R</a></li>
</ul></li>
<li class="chapter" data-level="41" data-path="imbalanced-data.html"><a href="imbalanced-data.html"><i class="fa fa-check"></i><b>41</b> Imbalanced Data</a>
<ul>
<li class="chapter" data-level="41.1" data-path="imbalanced-data.html"><a href="imbalanced-data.html#smote"><i class="fa fa-check"></i><b>41.1</b> <code>SMOTE</code></a></li>
<li class="chapter" data-level="41.2" data-path="imbalanced-data.html"><a href="imbalanced-data.html#fraud-detection"><i class="fa fa-check"></i><b>41.2</b> Fraud detection</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/yaydede/ToolShed" target="blank">&copy; 2020 - 2022 Yigit Aydede</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Tool Shed for Applied Data Analytics with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="preliminaries" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Preliminaries<a href="preliminaries.html#preliminaries" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This chapter will review some basic concepts in statistics. For now, don’t stress about understanding the code chunks. As you study and practice R more (See R Labs at the end of the book), the codes here will become clearer.</p>
<div id="data-and-dataset-types" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Data and dataset types<a href="preliminaries.html#data-and-dataset-types" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>R has a number of basic data types.</p>
<ul>
<li><strong>Numeric</strong> : Also known as Double. The default type when dealing with numbers. 1,1.0,42.5<br />
</li>
<li><strong>Integer</strong>: 1L,2L,42L<br />
</li>
<li><strong>Complex</strong>: 4 + 2i<br />
</li>
<li><strong>Logical</strong>: Two possible values: TRUE and FALSE. <code>NA</code> is also considered logical.<br />
</li>
<li><strong>Character</strong>: “a”,“Statistics”,“1plus2.”</li>
</ul>
<p>Data can also be classified as <strong>numeric</strong> (what’s your age?) and <strong>categorical</strong> (Do you have a car?)</p>
<p>R also has a number of basic data structures. A data structure is either <strong>homogeneous</strong> (all elements are of the same data type) or <strong>heterogeneous</strong> (elements can be of more than one data type): You can think each data structure as <strong>data container</strong> where you data is stored. Here are the main “container” or data structures. Think it as Stata or Excel spread-sheets.</p>
<ul>
<li><strong>Vector</strong>: 1 dimension (column OR row) and homogeneous. That is every element of the vector has to be the same type. Each vector can be thought of as a variable.</li>
<li><strong>Matrix</strong>: 2 dimensions (column AND row) and homogeneous. That is every element of the matrix has to be the same type.</li>
<li><strong>Data Frame</strong>: 2 dimensions (column AND row) and heterogeneous. That is every element of the data frame doesn’t have to be the same type. This is the main difference between a matrix and a data frame. Data frames are the most common data structure in any data analysis.</li>
<li><strong>List</strong>: 1 dimension and heterogeneous. Data can be multiple data structures.</li>
<li><strong>Array</strong>: 3+ dimensions and homogeneous.</li>
</ul>
<p>In this book, we most frequently work with data frames.</p>
<p>When using data, there are three things we like to do:</p>
<ul>
<li>Look at the raw data.<br />
</li>
<li>Understand the data. (What are the variables?)<br />
</li>
<li>Visualize the data.</li>
</ul>
<p>To look at the data, we have two useful commands: <code>head()</code> and <code>str()</code>, as seen in the examples below. <code>head()</code> allows us to see the first few data points in a dataset. <code>str()</code> allows us to see the structure of the data, including what data types are used. Using <code>str()</code> we can identify the <strong>mtcars</strong> dataset only includes numeric variables, and is structured in a data frame structure.</p>
<p><strong>Cross-Sectional</strong></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="preliminaries.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(datasets)</span>
<span id="cb1-2"><a href="preliminaries.html#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="preliminaries.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mtcars)</span></code></pre></div>
<pre><code>##                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
## Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="preliminaries.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mtcars)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    32 obs. of  11 variables:
##  $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
##  $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
##  $ disp: num  160 160 108 258 360 ...
##  $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
##  $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
##  $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
##  $ qsec: num  16.5 17 18.6 19.4 17 ...
##  $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
##  $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
##  $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
##  $ carb: num  4 4 1 1 2 1 4 2 2 4 ...</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="preliminaries.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mtcars)</span></code></pre></div>
<pre><code>##       mpg             cyl             disp             hp       
##  Min.   :10.40   Min.   :4.000   Min.   : 71.1   Min.   : 52.0  
##  1st Qu.:15.43   1st Qu.:4.000   1st Qu.:120.8   1st Qu.: 96.5  
##  Median :19.20   Median :6.000   Median :196.3   Median :123.0  
##  Mean   :20.09   Mean   :6.188   Mean   :230.7   Mean   :146.7  
##  3rd Qu.:22.80   3rd Qu.:8.000   3rd Qu.:326.0   3rd Qu.:180.0  
##  Max.   :33.90   Max.   :8.000   Max.   :472.0   Max.   :335.0  
##       drat             wt             qsec             vs        
##  Min.   :2.760   Min.   :1.513   Min.   :14.50   Min.   :0.0000  
##  1st Qu.:3.080   1st Qu.:2.581   1st Qu.:16.89   1st Qu.:0.0000  
##  Median :3.695   Median :3.325   Median :17.71   Median :0.0000  
##  Mean   :3.597   Mean   :3.217   Mean   :17.85   Mean   :0.4375  
##  3rd Qu.:3.920   3rd Qu.:3.610   3rd Qu.:18.90   3rd Qu.:1.0000  
##  Max.   :4.930   Max.   :5.424   Max.   :22.90   Max.   :1.0000  
##        am              gear            carb      
##  Min.   :0.0000   Min.   :3.000   Min.   :1.000  
##  1st Qu.:0.0000   1st Qu.:3.000   1st Qu.:2.000  
##  Median :0.0000   Median :4.000   Median :2.000  
##  Mean   :0.4062   Mean   :3.688   Mean   :2.812  
##  3rd Qu.:1.0000   3rd Qu.:4.000   3rd Qu.:4.000  
##  Max.   :1.0000   Max.   :5.000   Max.   :8.000</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="preliminaries.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mtcars[,<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">4</span>)])</span></code></pre></div>
<p><img src="YA_TextBook_files/figure-html/stat1-1.png" width="672" /></p>
<p><strong>Time-series</strong></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="preliminaries.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airquality)</span></code></pre></div>
<pre><code>##   Ozone Solar.R Wind Temp Month Day
## 1    41     190  7.4   67     5   1
## 2    36     118  8.0   72     5   2
## 3    12     149 12.6   74     5   3
## 4    18     313 11.5   62     5   4
## 5    NA      NA 14.3   56     5   5
## 6    28      NA 14.9   66     5   6</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="preliminaries.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(airquality)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    153 obs. of  6 variables:
##  $ Ozone  : int  41 36 12 18 NA 28 23 19 8 NA ...
##  $ Solar.R: int  190 118 149 313 NA NA 299 99 19 194 ...
##  $ Wind   : num  7.4 8 12.6 11.5 14.3 14.9 8.6 13.8 20.1 8.6 ...
##  $ Temp   : int  67 72 74 62 56 66 65 59 61 69 ...
##  $ Month  : int  5 5 5 5 5 5 5 5 5 5 ...
##  $ Day    : int  1 2 3 4 5 6 7 8 9 10 ...</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="preliminaries.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(airquality)</span></code></pre></div>
<pre><code>##      Ozone           Solar.R           Wind             Temp      
##  Min.   :  1.00   Min.   :  7.0   Min.   : 1.700   Min.   :56.00  
##  1st Qu.: 18.00   1st Qu.:115.8   1st Qu.: 7.400   1st Qu.:72.00  
##  Median : 31.50   Median :205.0   Median : 9.700   Median :79.00  
##  Mean   : 42.13   Mean   :185.9   Mean   : 9.958   Mean   :77.88  
##  3rd Qu.: 63.25   3rd Qu.:258.8   3rd Qu.:11.500   3rd Qu.:85.00  
##  Max.   :168.00   Max.   :334.0   Max.   :20.700   Max.   :97.00  
##  NA&#39;s   :37       NA&#39;s   :7                                       
##      Month            Day      
##  Min.   :5.000   Min.   : 1.0  
##  1st Qu.:6.000   1st Qu.: 8.0  
##  Median :7.000   Median :16.0  
##  Mean   :6.993   Mean   :15.8  
##  3rd Qu.:8.000   3rd Qu.:23.0  
##  Max.   :9.000   Max.   :31.0  
## </code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="preliminaries.html#cb14-1" aria-hidden="true" tabindex="-1"></a>airquality<span class="sc">$</span>date <span class="ot">&lt;-</span> airquality<span class="sc">$</span>Month<span class="sc">*</span><span class="dv">10</span><span class="sc">+</span>airquality<span class="sc">$</span>Day</span>
<span id="cb14-2"><a href="preliminaries.html#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(airquality<span class="sc">$</span>date, airquality<span class="sc">$</span>Ozone)</span></code></pre></div>
<p><img src="YA_TextBook_files/figure-html/stat3-1.png" width="672" /></p>
<p>This was just a simple time-series data presentation. In Part VIII, we will see more advance ways to handle time-series data. Moreover, dates and times can be handled by various packages/functions in R, like <code>lubridate</code> (see <a href="https://lubridate.tidyverse.org" class="uri">https://lubridate.tidyverse.org</a>).</p>
<p>Here are some examples</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="preliminaries.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb15-2"><a href="preliminaries.html#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># get current system date</span></span>
<span id="cb15-3"><a href="preliminaries.html#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">Sys.Date</span>() </span></code></pre></div>
<pre><code>## [1] &quot;2022-09-04&quot;</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="preliminaries.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get current system time</span></span>
<span id="cb17-2"><a href="preliminaries.html#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Sys.time</span>()</span></code></pre></div>
<pre><code>## [1] &quot;2022-09-04 07:21:52 ADT&quot;</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="preliminaries.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#lubridate</span></span>
<span id="cb19-2"><a href="preliminaries.html#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">now</span>()</span></code></pre></div>
<pre><code>## [1] &quot;2022-09-04 07:21:52 ADT&quot;</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="preliminaries.html#cb21-1" aria-hidden="true" tabindex="-1"></a>dates <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;2022-07-11&quot;</span>, <span class="st">&quot;2012-04-19&quot;</span>, <span class="st">&quot;2017-03-08&quot;</span>)</span>
<span id="cb21-2"><a href="preliminaries.html#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="preliminaries.html#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># extract years from dates</span></span>
<span id="cb21-4"><a href="preliminaries.html#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">year</span>(dates)</span></code></pre></div>
<pre><code>## [1] 2022 2012 2017</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="preliminaries.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extract months from dates</span></span>
<span id="cb23-2"><a href="preliminaries.html#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">month</span>(dates)</span></code></pre></div>
<pre><code>## [1] 7 4 3</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="preliminaries.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extract days from dates</span></span>
<span id="cb25-2"><a href="preliminaries.html#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mday</span>(dates)</span></code></pre></div>
<pre><code>## [1] 11 19  8</code></pre>
<p><strong>Panel</strong><br />
Panel data (also known as longitudinal data) is a dataset in which the behavior of multiple entities are observed across time. These entities could be states, companies, individuals, countries, etc. Note in the example below, two countries (“A”, and “B”) have variables observed over a time span between 1990 to 1999.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="preliminaries.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(foreign)</span>
<span id="cb27-2"><a href="preliminaries.html#cb27-2" aria-hidden="true" tabindex="-1"></a>panel <span class="ot">&lt;-</span> <span class="fu">read.dta</span>(<span class="st">&quot;http://dss.princeton.edu/training/Panel101.dta&quot;</span>)</span>
<span id="cb27-3"><a href="preliminaries.html#cb27-3" aria-hidden="true" tabindex="-1"></a>panel[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>]</span></code></pre></div>
<pre><code>##    country year           y y_bin          x1         x2          x3
## 1        A 1990  1342787840     1  0.27790365 -1.1079559  0.28255358
## 2        A 1991 -1899660544     0  0.32068470 -0.9487200  0.49253848
## 3        A 1992   -11234363     0  0.36346573 -0.7894840  0.70252335
## 4        A 1993  2645775360     1  0.24614404 -0.8855330 -0.09439092
## 5        A 1994  3008334848     1  0.42462304 -0.7297683  0.94613063
## 6        A 1995  3229574144     1  0.47721413 -0.7232460  1.02968037
## 7        A 1996  2756754176     1  0.49980500 -0.7815716  1.09228814
## 8        A 1997  2771810560     1  0.05162839 -0.7048455  1.41590083
## 9        A 1998  3397338880     1  0.36641079 -0.6983712  1.54872274
## 10       A 1999    39770336     1  0.39584252 -0.6431540  1.79419804
## 11       B 1990 -5934699520     0 -0.08184998  1.4251202  0.02342812
## 12       B 1991  -711623744     0  0.10616001  1.6496018  0.26036251
## 13       B 1992 -1933116160     0  0.35378519  1.5937191 -0.23439877
## 14       B 1993  3072741632     1  0.72677696  1.6917576  0.25622433
## 15       B 1994  3768078848     1  0.71939486  1.7414261  0.41174951
## 16       B 1995  2837581312     1  0.67154658  1.7083139  0.53584301
## 17       B 1996   577199360     1  0.81985730  1.5324961 -0.49964902
## 18       B 1997  1786851584     1  0.88016719  1.5021962 -0.57626772
## 19       B 1998  -149072048     0  0.70451611  1.4236463 -0.44841924
## 20       B 1999 -1174480128     0  0.23696731  1.4545859 -0.04936399</code></pre>
</div>
<div id="plots" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Plots<a href="preliminaries.html#plots" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Often, a proper visualization can illuminate features of the data that can inform further analysis. We will look at four methods of visualizing data that we will use throughout the book:<br />
- <strong>Histograms</strong><br />
- <strong>Barplots</strong><br />
- <strong>Boxplots</strong><br />
- <strong>Scatterplots</strong></p>
<p>We can use the vehicle data, <code>mpg</code> inside the <code>ggplot2</code> package. To begin, we can get a sense of the data by looking at the first few data points and some summary statistics.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="preliminaries.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb29-2"><a href="preliminaries.html#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mpg, <span class="at">n=</span>20L)</span></code></pre></div>
<pre><code>## # A tibble: 20 × 11
##    manufacturer model      displ  year   cyl trans drv     cty   hwy fl    class
##    &lt;chr&gt;        &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; &lt;chr&gt;
##  1 audi         a4           1.8  1999     4 auto… f        18    29 p     comp…
##  2 audi         a4           1.8  1999     4 manu… f        21    29 p     comp…
##  3 audi         a4           2    2008     4 manu… f        20    31 p     comp…
##  4 audi         a4           2    2008     4 auto… f        21    30 p     comp…
##  5 audi         a4           2.8  1999     6 auto… f        16    26 p     comp…
##  6 audi         a4           2.8  1999     6 manu… f        18    26 p     comp…
##  7 audi         a4           3.1  2008     6 auto… f        18    27 p     comp…
##  8 audi         a4 quattro   1.8  1999     4 manu… 4        18    26 p     comp…
##  9 audi         a4 quattro   1.8  1999     4 auto… 4        16    25 p     comp…
## 10 audi         a4 quattro   2    2008     4 manu… 4        20    28 p     comp…
## 11 audi         a4 quattro   2    2008     4 auto… 4        19    27 p     comp…
## 12 audi         a4 quattro   2.8  1999     6 auto… 4        15    25 p     comp…
## 13 audi         a4 quattro   2.8  1999     6 manu… 4        17    25 p     comp…
## 14 audi         a4 quattro   3.1  2008     6 auto… 4        17    25 p     comp…
## 15 audi         a4 quattro   3.1  2008     6 manu… 4        15    25 p     comp…
## 16 audi         a6 quattro   2.8  1999     6 auto… 4        15    24 p     mids…
## 17 audi         a6 quattro   3.1  2008     6 auto… 4        17    25 p     mids…
## 18 audi         a6 quattro   4.2  2008     8 auto… 4        16    23 p     mids…
## 19 chevrolet    c1500 sub…   5.3  2008     8 auto… r        14    20 r     suv  
## 20 chevrolet    c1500 sub…   5.3  2008     8 auto… r        11    15 e     suv</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="preliminaries.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mpg)</span></code></pre></div>
<pre><code>##  manufacturer          model               displ            year     
##  Length:234         Length:234         Min.   :1.600   Min.   :1999  
##  Class :character   Class :character   1st Qu.:2.400   1st Qu.:1999  
##  Mode  :character   Mode  :character   Median :3.300   Median :2004  
##                                        Mean   :3.472   Mean   :2004  
##                                        3rd Qu.:4.600   3rd Qu.:2008  
##                                        Max.   :7.000   Max.   :2008  
##       cyl           trans               drv                 cty       
##  Min.   :4.000   Length:234         Length:234         Min.   : 9.00  
##  1st Qu.:4.000   Class :character   Class :character   1st Qu.:14.00  
##  Median :6.000   Mode  :character   Mode  :character   Median :17.00  
##  Mean   :5.889                                         Mean   :16.86  
##  3rd Qu.:8.000                                         3rd Qu.:19.00  
##  Max.   :8.000                                         Max.   :35.00  
##       hwy             fl               class          
##  Min.   :12.00   Length:234         Length:234        
##  1st Qu.:18.00   Class :character   Class :character  
##  Median :24.00   Mode  :character   Mode  :character  
##  Mean   :23.44                                        
##  3rd Qu.:27.00                                        
##  Max.   :44.00</code></pre>
<p>When visualizing a single numerical variable, a histogram would be very handy:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="preliminaries.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(mpg<span class="sc">$</span>cty, <span class="at">xlab =</span> <span class="st">&quot;Miles Per Gallon (City)&quot;</span>,</span>
<span id="cb33-2"><a href="preliminaries.html#cb33-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Histogram of MPG (City)&quot;</span>, <span class="at">breaks =</span> <span class="dv">12</span>,</span>
<span id="cb33-3"><a href="preliminaries.html#cb33-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">&quot;dodgerblue&quot;</span>,<span class="at">cex.main=</span><span class="dv">1</span>, <span class="at">cex.lab=</span>.<span class="dv">75</span>, <span class="at">cex.axis=</span><span class="fl">0.75</span>,</span>
<span id="cb33-4"><a href="preliminaries.html#cb33-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">border =</span> <span class="st">&quot;darkorange&quot;</span>)</span></code></pre></div>
<p><img src="YA_TextBook_files/figure-html/stat6-1.png" width="672" /></p>
<p>Similar to a histogram, a barplot provides a visual summary of a categorical variable, or a numeric variable with a finite number of values, like a ranking from 1 to 10.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="preliminaries.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">table</span>(mpg<span class="sc">$</span>drv), </span>
<span id="cb34-2"><a href="preliminaries.html#cb34-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">&quot;Drivetrain (f = FWD, r = RWD, 4 = 4WD)&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Frequency&quot;</span>,</span>
<span id="cb34-3"><a href="preliminaries.html#cb34-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">&quot;Drivetrains&quot;</span>,</span>
<span id="cb34-4"><a href="preliminaries.html#cb34-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">&quot;dodgerblue&quot;</span>,<span class="at">cex.main=</span><span class="dv">1</span>, <span class="at">cex.lab=</span>.<span class="dv">75</span>, <span class="at">cex.axis=</span><span class="fl">0.75</span>,</span>
<span id="cb34-5"><a href="preliminaries.html#cb34-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">border =</span> <span class="st">&quot;darkorange&quot;</span>)</span></code></pre></div>
<p><img src="YA_TextBook_files/figure-html/stat7-1.png" width="672" /></p>
<p>To visualize the relationship between a numerical and categorical variable, we will use a boxplot. In the <code>mpg</code> dataset, the <code>drv</code> variable takes a small, finite number of values. A car can only be front-wheel drive, 4-wheel drive, or rear-wheel drive.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="preliminaries.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(hwy <span class="sc">~</span> drv, <span class="at">data =</span> mpg,</span>
<span id="cb35-2"><a href="preliminaries.html#cb35-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">&quot;Drivetrain (f = FWD, r = RWD, 4 = 4WD)&quot;</span>,</span>
<span id="cb35-3"><a href="preliminaries.html#cb35-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">&quot;Miles Per Gallon (Highway)&quot;</span>,</span>
<span id="cb35-4"><a href="preliminaries.html#cb35-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">&quot;MPG (Highway) vs Drivetrain&quot;</span>,</span>
<span id="cb35-5"><a href="preliminaries.html#cb35-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">pch =</span> <span class="dv">20</span>, <span class="at">cex =</span><span class="dv">2</span>,<span class="at">cex.main=</span><span class="dv">1</span>, <span class="at">cex.lab=</span>.<span class="dv">75</span>, <span class="at">cex.axis=</span><span class="fl">0.75</span>,</span>
<span id="cb35-6"><a href="preliminaries.html#cb35-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">&quot;darkorange&quot;</span>, <span class="at">border =</span> <span class="st">&quot;dodgerblue&quot;</span>)</span></code></pre></div>
<p><img src="YA_TextBook_files/figure-html/stat8-1.png" width="672" /></p>
<p>Finally, to visualize the relationship between two numeric variables we will use a scatterplot.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="preliminaries.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hwy <span class="sc">~</span> displ, <span class="at">data =</span> mpg,</span>
<span id="cb36-2"><a href="preliminaries.html#cb36-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Engine Displacement (in Liters)&quot;</span>,</span>
<span id="cb36-3"><a href="preliminaries.html#cb36-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Miles Per Gallon (Highway)&quot;</span>,</span>
<span id="cb36-4"><a href="preliminaries.html#cb36-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;MPG (Highway) vs Engine Displacement&quot;</span>,</span>
<span id="cb36-5"><a href="preliminaries.html#cb36-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">20</span>, <span class="at">cex =</span> <span class="dv">2</span>, <span class="at">cex.main=</span><span class="dv">1</span>, <span class="at">cex.lab=</span>.<span class="dv">75</span>, <span class="at">cex.axis=</span><span class="fl">0.75</span>,</span>
<span id="cb36-6"><a href="preliminaries.html#cb36-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">&quot;dodgerblue&quot;</span>)</span></code></pre></div>
<p><img src="YA_TextBook_files/figure-html/stat9-1.png" width="672" /></p>
<p>While visualization is not enough to draw definitive conclusions, it can help us identify insights that can inform our deeper analysis. R is well-know for its graphical capabilities. The package <code>ggplot</code> is the main tool for more advance graphical representations that we will see later.</p>
</div>
<div id="probability-distributions-with-r" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Probability Distributions with R<a href="preliminaries.html#probability-distributions-with-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We often want to make probabilistic statements based on a distribution. Typically, we will want to know one of four things:</p>
<ul>
<li>The probability density function (pdf) at a particular value.<br />
</li>
<li>The cumulative probability distribution (cdf) at a particular value.<br />
</li>
<li>The quantile value corresponding to a particular probability.<br />
</li>
<li>A random draw of values from a particular distribution.</li>
</ul>
<p>The general naming structure of the relevant R functions is:</p>
<ul>
<li><code>dname</code> calculates density (pdf) at input <span class="math inline">\(x\)</span>.<br />
</li>
<li><code>pname</code> calculates distribution (cdf) at input <span class="math inline">\(x\)</span>.<br />
</li>
<li><code>qname</code> calculates the quantile at an input probability.<br />
</li>
<li><code>rname</code> generates a random draw from a particular distribution.</li>
</ul>
<p>where <code>name</code> represents the name of the given distribution, like <code>rnorm</code> for a random draw from a normal distribution</p>
<p>For example, consider a random variable <span class="math inline">\(X\)</span>:</p>
<p><span class="math display">\[
X \sim N\left(\mu=2, \sigma^{2}=25\right)
\]</span></p>
<p>To calculate the value of the pdf at <span class="math inline">\(x = 4\)</span>, that is, the height of the curve at <span class="math inline">\(x = 4\)</span>, use <code>dnorm()</code>:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="preliminaries.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dnorm</span>(<span class="at">x =</span> <span class="dv">4</span>, <span class="at">mean =</span> <span class="dv">2</span>, <span class="at">sd =</span> <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## [1] 0.07365403</code></pre>
<p>Note that R uses the standard deviation.</p>
<p>To calculate the value of the cdf at <span class="math inline">\(x = 4\)</span>, that is, <span class="math inline">\(P(X \leq{4})\)</span>, the probability that <span class="math inline">\(X\)</span> is less than or equal to 4, use <code>pnorm()</code>:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="preliminaries.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="at">q =</span> <span class="dv">4</span>, <span class="at">mean =</span> <span class="dv">2</span>, <span class="at">sd =</span> <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## [1] 0.6554217</code></pre>
<p>Or, to calculate the quantile for probability 0.975, use <code>qnorm()</code>:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="preliminaries.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="at">p =</span> <span class="fl">0.975</span>, <span class="at">mean =</span> <span class="dv">2</span>, <span class="at">sd =</span> <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## [1] 11.79982</code></pre>
<p>Lastly, to generate a random sample of size n = 10, use <code>rnorm()</code></p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="preliminaries.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">10</span>, <span class="at">mean =</span> <span class="dv">2</span>, <span class="at">sd =</span> <span class="dv">5</span>)</span></code></pre></div>
<pre><code>##  [1]  4.9897470  8.6316907 -0.1421002  4.5619919 -0.7607317  5.9018914
##  [7]  4.7924889 11.3952540  4.2463310  0.5183168</code></pre>
<p>These functions exist for many other distributions such as: <code>binom</code> (Binomial), <code>t</code> (Student’s t), <code>pois</code> (Poisson), <code>f</code> (F), <code>chisq</code> (Chi-Squared).</p>
</div>
<div id="regressions" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Regressions<a href="preliminaries.html#regressions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Regressions allow us to make estimations of the relationships between variables. Let’s consider a simple example of how the speed of a car affects its stopping distance. To examine this relationship, we will use the <code>cars</code> data set. We can start by getting some basic information about the data using <code>str()</code> and <code>summary()</code> again.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="preliminaries.html#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(cars)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    50 obs. of  2 variables:
##  $ speed: num  4 4 7 7 8 9 10 10 10 11 ...
##  $ dist : num  2 10 4 22 16 10 18 26 34 17 ...</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="preliminaries.html#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cars)</span></code></pre></div>
<pre><code>##      speed           dist       
##  Min.   : 4.0   Min.   :  2.00  
##  1st Qu.:12.0   1st Qu.: 26.00  
##  Median :15.0   Median : 36.00  
##  Mean   :15.4   Mean   : 42.98  
##  3rd Qu.:19.0   3rd Qu.: 56.00  
##  Max.   :25.0   Max.   :120.00</code></pre>
<p>Note that the variable names are quite long. To make them easier to work with, we can change them. We do this first by making a new data frame so we don’t alter the initial data when making changes. Then we apply new column names to it with the <code>colnames()</code> function. Our new names will be <code>speed</code> and <code>dist</code>.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="preliminaries.html#cb49-1" aria-hidden="true" tabindex="-1"></a>carsDF <span class="ot">&lt;-</span> cars</span>
<span id="cb49-2"><a href="preliminaries.html#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(carsDF) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;speed&quot;</span>, <span class="st">&quot;dist&quot;</span>)</span></code></pre></div>
<p>Finally, we can plot the speed and stopping distance in a scatterplot to get a sense of their relationship before proceeding with a formal regression.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="preliminaries.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dist <span class="sc">~</span> speed, <span class="at">data =</span> carsDF,</span>
<span id="cb50-2"><a href="preliminaries.html#cb50-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Speed (in Miles Per Hour)&quot;</span>,</span>
<span id="cb50-3"><a href="preliminaries.html#cb50-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Stopping Distance (in Feet)&quot;</span>,</span>
<span id="cb50-4"><a href="preliminaries.html#cb50-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Stopping Distance vs Speed&quot;</span>,</span>
<span id="cb50-5"><a href="preliminaries.html#cb50-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">20</span>, <span class="at">cex =</span> <span class="dv">2</span>,<span class="at">cex.main=</span><span class="dv">1</span>,</span>
<span id="cb50-6"><a href="preliminaries.html#cb50-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex.lab=</span>.<span class="dv">75</span>, <span class="at">cex.axis=</span><span class="fl">0.75</span>, <span class="at">col =</span> <span class="st">&quot;grey&quot;</span>)</span></code></pre></div>
<p><img src="YA_TextBook_files/figure-html/stat15-1.png" width="672" /></p>
<p>This visualization suggests there could be a relationship.</p>
<p>In this example, we are interested in using the predictor variable <code>speed</code> to predict and explain the response variable <code>dist</code>. We could express the relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> using the following “Data Generating Process” (DGP):</p>
<p><span class="math display" id="eq:2-1">\[\begin{equation}
Y=f(X)+\epsilon
  \tag{2.1}
\end{equation}\]</span></p>
<p>Here <span class="math inline">\(Y\)</span> from 2.1 is the outcome determined by two parts: <span class="math inline">\(f(X)\)</span>, which is the deterministic part (a.k.a Data Generating Model - DGM) and <span class="math inline">\(\epsilon\)</span> the random part that makes the outcome different for the same <span class="math inline">\(X\)</span> for each observation. What’s <span class="math inline">\(f(X)\)</span>? We will see later that this question is very important. For now, however, we assume that <span class="math inline">\(f(X)\)</span> is linear as</p>
<p><span class="math display" id="eq:2-2">\[\begin{equation}
f(X)=\beta_{0}+\beta_{1} x_{i}.
  \tag{2.2}
\end{equation}\]</span></p>
<p>And,</p>
<p><span class="math display">\[
\begin{array}{l}{\qquad Y_{i}=\beta_{0}+\beta_{1} x_{i}+\epsilon_{i}} \ {\text { where }} \ {\qquad \epsilon_{i} \sim N\left(0, \sigma^{2}\right)}\end{array}
\]</span>
We could think that <span class="math inline">\(Y\)</span> has different distribution for each value of <span class="math inline">\(X\)</span>. Hence, <span class="math inline">\(f(x)\)</span> becomes the conditional mean of <span class="math inline">\(Y\)</span> given <span class="math inline">\(X\)</span>.</p>
<p><span class="math display">\[
f(X) = \mathrm{E}\left[Y | X=x_{i}\right]=\beta_{0}+\beta_{1} x_{i},
\]</span></p>
<p>which means that <span class="math inline">\(\mathrm{E}\left[\epsilon | X=x_{i}\right]=0\)</span>. This model, which is also called as the population regression function (PRF), has three parameters to be estimated: <span class="math inline">\(\beta_{0}\)</span>, <span class="math inline">\(\beta_{1}\)</span>, and <span class="math inline">\(\sigma^{2}\)</span>, which are fixed but unknown constants. The coefficient <span class="math inline">\(\beta_{1}\)</span> defines the relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. Inferential statistics deals with estimating these population parameters using a sample drawn from the population. The statistical inference requires an estimator of a population parameter to be BLUE (Best Linear Unbiased Estimator) which is usually challenging to satisfy. A BLU estimator also requires several assumptions on PRF. These include that:</p>
<ul>
<li>The errors are <strong>independent</strong> (no serial correlation).<br />
</li>
<li>The errors are <strong>identically</strong> distributed (constant variance of <span class="math inline">\(Y\)</span> for different values of <span class="math inline">\(X\)</span>) .</li>
</ul>
<p>How do we actually find a line that represents the best relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> best? We must find a line that minimizes the sum of squared “errors”. This is the Ordinary Least Squares (OLS) method:</p>
<p><span class="math display" id="eq:2-3">\[\begin{equation}
\underset{\beta_{0}, \beta_{1}}{\operatorname{argmin}} \sum_{i=1}^{n}\left(y_{i}-\left(\beta_{0}+\beta_{1} x_{i}\right)\right)^{2}
  \tag{2.3}
\end{equation}\]</span></p>
<p>Using R, we can apply this method very simply with a bit of code.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="preliminaries.html#cb51-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(dist <span class="sc">~</span> speed, <span class="at">data =</span> carsDF)</span>
<span id="cb51-2"><a href="preliminaries.html#cb51-2" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">coef</span>(model)</span>
<span id="cb51-3"><a href="preliminaries.html#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(carsDF, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">pch =</span> <span class="dv">20</span>)</span>
<span id="cb51-4"><a href="preliminaries.html#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(b, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="dv">5</span>)</span></code></pre></div>
<p><img src="YA_TextBook_files/figure-html/stat16-1.png" width="672" /></p>
<p>Although we can see here the red line which minimizes the sum of squared error using the OLS method, we can try understand this problem mathematically.</p>
<div id="ordinary-least-squares-ols" class="section level3 hasAnchor" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Ordinary Least Squares (OLS)<a href="preliminaries.html#ordinary-least-squares-ols" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The solution to this problem starts with defining the loss function, finding the first order conditions (F.O.C.) and solving them through <strong>normal equations</strong>.</p>
<p><span class="math display" id="eq:2-4">\[\begin{equation}
f\left(\beta_{0}, \beta_{1}\right)=\sum_{i=1}^{n}\left(y_{i}-\left(\beta_{0}+\beta_{1}
x_{i}\right)\right)^{2}=\sum_{i=1}^{n}\left(y_{i}-\beta_{0}-\beta_{1} x_{i}\right)^{2}
  \tag{2.4}
\end{equation}\]</span></p>
<p><span class="math display">\[
\begin{aligned} \frac{\partial f}{\partial \beta_{0}} &amp;=-2 \sum_{i=1}^{n}\left(y_{i}-\beta_{0}-\beta_{1} x_{i}\right) \\ \frac{\partial f}{\partial \beta_{1}} &amp;=-2 \sum_{i=1}^{n}\left(x_{i}\right)\left(y_{i}-\beta_{0}-\beta_{1} x_{i}\right) \end{aligned}
\]</span></p>
<p>Here are 2 equations and 2 unknowns:</p>
<p><span class="math display">\[
\begin{array}{c}{\sum_{i=1}^{n}\left(y_{i}-\beta_{0}-\beta_{1} x_{i}\right)=0} \end{array}
\]</span></p>
<p><span class="math display">\[
\begin{array}{c}{\sum_{i=1}^{n}\left(x_{i}\right)\left(y_{i}-\beta_{0}-\beta_{1} x_{i}\right)=0}\end{array}
\]</span></p>
<p>Which can be expressed:</p>
<p><span class="math display" id="eq:2-5">\[\begin{equation}
\begin{array}{c}{n \beta_{0}+\beta_{1} \sum_{i=1}^{n} x_{i}=\sum_{i=1}^{n} y_{i}} \end{array}
  \tag{2.5}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:2-6">\[\begin{equation}
\begin{array}{c}{\beta_{0} \sum_{i=1}^{n} x_{i}+\beta_{1} \sum_{i=1}^{n} x_{i}^{2}=\sum_{i=1}^{n} x_{i} y_{i}}\end{array}
  \tag{2.6}
\end{equation}\]</span></p>
<p>These functions (2.5 and 2.6) are also called <strong>normal equations</strong>. Solving them gives us:</p>
<p><span class="math display" id="eq:2-7">\[\begin{equation}
\beta_{1}=\frac{\text{cov}(Y,X)}{\text{var}(X)}
  \tag{2.7}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:2-8">\[\begin{equation}
\beta_{0}=\overline{y}-\beta_{1} \overline{x}
  \tag{2.8}
\end{equation}\]</span></p>
<p>As this is simply a review, it won’t be covered in more depth here. Let’s use these variance/covariance values to get the parameters.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="preliminaries.html#cb52-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> carsDF<span class="sc">$</span>speed</span>
<span id="cb52-2"><a href="preliminaries.html#cb52-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> carsDF<span class="sc">$</span>dist</span>
<span id="cb52-3"><a href="preliminaries.html#cb52-3" aria-hidden="true" tabindex="-1"></a>Sxy <span class="ot">&lt;-</span> <span class="fu">sum</span>((x <span class="sc">-</span> <span class="fu">mean</span>(x)) <span class="sc">*</span> (y <span class="sc">-</span> <span class="fu">mean</span>(y)))</span>
<span id="cb52-4"><a href="preliminaries.html#cb52-4" aria-hidden="true" tabindex="-1"></a>Sxx <span class="ot">=</span> <span class="fu">sum</span>((x <span class="sc">-</span> <span class="fu">mean</span>(x)) <span class="sc">^</span> <span class="dv">2</span>) <span class="co">#Here to show, &quot;=&quot; would work as well</span></span>
<span id="cb52-5"><a href="preliminaries.html#cb52-5" aria-hidden="true" tabindex="-1"></a>Syy <span class="ot">&lt;-</span> <span class="fu">sum</span>((y <span class="sc">-</span> <span class="fu">mean</span>(y)) <span class="sc">^</span> <span class="dv">2</span>)</span>
<span id="cb52-6"><a href="preliminaries.html#cb52-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-7"><a href="preliminaries.html#cb52-7" aria-hidden="true" tabindex="-1"></a>beta_1 <span class="ot">&lt;-</span> Sxy <span class="sc">/</span> Sxx</span>
<span id="cb52-8"><a href="preliminaries.html#cb52-8" aria-hidden="true" tabindex="-1"></a>beta_0 <span class="ot">&lt;-</span> <span class="fu">mean</span>(y) <span class="sc">-</span> beta_1 <span class="sc">*</span> <span class="fu">mean</span>(x)</span>
<span id="cb52-9"><a href="preliminaries.html#cb52-9" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(beta_0, beta_1)</span></code></pre></div>
<pre><code>## [1] -17.579095   3.932409</code></pre>
<p>Instead of coding each of the steps ourselves, we can also use the <code>lm()</code> function to achieve the same thing.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="preliminaries.html#cb54-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(dist <span class="sc">~</span> speed, <span class="at">data =</span> carsDF)</span>
<span id="cb54-2"><a href="preliminaries.html#cb54-2" aria-hidden="true" tabindex="-1"></a>model</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = dist ~ speed, data = carsDF)
## 
## Coefficients:
## (Intercept)        speed  
##     -17.579        3.932</code></pre>
<p>The slope parameter (<span class="math inline">\(\beta_1\)</span>) tells us that the stopping distance is predicted to increase by <span class="math inline">\(3.93\)</span> feet on average for an increase in speed of one mile per hour. The intercept parameter tells us that when the car’s speed is zero, it moves backwards. This indicates a modeling problem. One way to handle it to remove the intercept from the model that starts from the origin.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="preliminaries.html#cb56-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> carsDF<span class="sc">$</span>speed</span>
<span id="cb56-2"><a href="preliminaries.html#cb56-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> carsDF<span class="sc">$</span>dist</span>
<span id="cb56-3"><a href="preliminaries.html#cb56-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-4"><a href="preliminaries.html#cb56-4" aria-hidden="true" tabindex="-1"></a>beta_1 <span class="ot">&lt;-</span> <span class="fu">sum</span>(x<span class="sc">*</span>y) <span class="sc">/</span> <span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb56-5"><a href="preliminaries.html#cb56-5" aria-hidden="true" tabindex="-1"></a>beta_1</span></code></pre></div>
<pre><code>## [1] 2.909132</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="preliminaries.html#cb58-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(dist <span class="sc">~</span> speed <span class="sc">-</span> <span class="dv">1</span>, <span class="at">data =</span> carsDF)</span>
<span id="cb58-2"><a href="preliminaries.html#cb58-2" aria-hidden="true" tabindex="-1"></a>model</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = dist ~ speed - 1, data = carsDF)
## 
## Coefficients:
## speed  
## 2.909</code></pre>
<p>As we can see changing the model affects the prediction. Unfortunately the single-variable case is usually not a realistic model to capture the determination of the output. Let’s use a better dataset, <code>mtcars</code>:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="preliminaries.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mtcars)</span></code></pre></div>
<pre><code>##                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
## Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="preliminaries.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mtcars)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    32 obs. of  11 variables:
##  $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
##  $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
##  $ disp: num  160 160 108 258 360 ...
##  $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
##  $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
##  $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
##  $ qsec: num  16.5 17 18.6 19.4 17 ...
##  $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
##  $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
##  $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
##  $ carb: num  4 4 1 1 2 1 4 2 2 4 ...</code></pre>
<p>We may want to model the fuel efficiency (<code>mpg</code>) of a car as a function of its weight (<code>wt</code>) and horse power (<code>hp</code>). We can do this using our method of normal equations.</p>
<p><span class="math display">\[
Y_{i}=\beta_{0}+\beta_{1} x_{i 1}+\beta_{2} x_{i 2}+\epsilon_{i}, \quad i=1,2, \ldots, n
\]</span></p>
<p><span class="math display">\[
f\left(\beta_{0}, \beta_{1}, \beta_{2}\right)=\sum_{i=1}^{n}\left(y_{i}-\left(\beta_{0}+\beta_{1} x_{i 1}+\beta_{2} x_{i 2}\right)\right)^{2}
\]</span></p>
<p><span class="math display">\[
\begin{aligned} \frac{\partial f}{\partial \beta_{0}} &amp;=0 \\ \frac{\partial f}{\partial \beta_{1}} &amp;=0 \\ \frac{\partial f}{\partial \beta_{2}} &amp;=0 \end{aligned}
\]</span></p>
<p><span class="math display">\[
\begin{array}{c}{n \beta_{0}+\beta_{1} \sum_{i=1}^{n} x_{i 1}+\beta_{2} \sum_{i=1}^{n} x_{i 2}=\sum_{i=1}^{n} y_{i}} \end{array}
\]</span>
<span class="math display">\[
\begin{array}{c}{\beta_{0} \sum_{i=1}^{n} x_{i 1}+\beta_{1} \sum_{i=1}^{n} x_{i 1}^{2}+\beta_{2} \sum_{i=1}^{n} x_{i 1} x_{i 2}=\sum_{i=1}^{n} x_{i 1} y_{i}} \end{array}
\]</span></p>
<p><span class="math display">\[
\begin{array}{c}{\beta_{0} \sum_{i=1}^{n} x_{i 2}+\beta_{1} \sum_{i=1}^{n} x_{i 1} x_{i 2}+\beta_{2} \sum_{i=1}^{n} x_{i 2}^{2}=\sum_{i=1}^{n} x_{i 2} y_{i}}\end{array}
\]</span></p>
<p>We now have three equations and three variables. While we could solve these ourselves, we can again let R solve them for us instead:</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="preliminaries.html#cb64-1" aria-hidden="true" tabindex="-1"></a>mpg_model <span class="ot">=</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt <span class="sc">+</span> hp, <span class="at">data =</span> mtcars)</span>
<span id="cb64-2"><a href="preliminaries.html#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mpg_model)</span></code></pre></div>
<pre><code>## (Intercept)          wt          hp 
## 37.22727012 -3.87783074 -0.03177295</code></pre>
<p>The details of these applications can be reviewed in the lab sessions at the end of the book. When the number of explanatory variables is too large, we have to apply a matrix approach to solve it.</p>
<p>Up to this point we used OLS that finds the parameters minimizing the residual sum of squares (RSS - or the sum of squared errors). The other method is called Maximum likelihood Estimator or MLE.</p>
</div>
<div id="maximum-likelihood-estimators" class="section level3 hasAnchor" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> Maximum Likelihood Estimators<a href="preliminaries.html#maximum-likelihood-estimators" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To characterize the distribution of a continuous random variable, you can use the probability density function (pdf). Recall that pdf of a random variable <span class="math inline">\(X \sim N\left(\mu, \sigma^{2}\right)\)</span> is given by:</p>
<p><span class="math display">\[
f_{x}\left(x ; \mu, \sigma^{2}\right)=\frac{1}{\sqrt{2 \pi \sigma^{2}}} \exp \left[-\frac{1}{2}\left(\frac{x_i-\mu}{\sigma}\right)^{2}\right]
\]</span>
In R, you can use <code>dnorm(x, mean, sd)</code> to calculate the pdf of normal distribution.</p>
<ul>
<li>The argument <span class="math inline">\(x\)</span> represent the location(s) at which to compute the pdf.</li>
<li>The arguments <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span> represent the mean and standard deviation of the normal distribution, respectively.</li>
</ul>
<p>For example, <code>dnorm (0, mean=1, sd=2)</code> computes the pdf at location 0 of <span class="math inline">\(N(1,4)\)</span>, normal distribution with mean 1 and variance 4. Let’s see examples of computing the pdf at 2 locations for.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="preliminaries.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dnorm</span>(<span class="dv">0</span>, <span class="at">mean =</span> <span class="dv">1</span>, <span class="at">sd =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.1760327</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="preliminaries.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dnorm</span>(<span class="dv">1</span>, <span class="at">mean =</span> <span class="dv">1</span>, <span class="at">sd =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.1994711</code></pre>
<p>In addition to computing the pdf at one location for a single normal distribution, <code>dnorm</code> also accepts vectors with more than one elements in all three arguments. For example, suppose that we have the following data, <span class="math inline">\(x\)</span>. We can now compute pdf values for each <span class="math inline">\(x\)</span>.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="preliminaries.html#cb70-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from=</span><span class="sc">-</span><span class="dv">10</span>,<span class="at">to=</span><span class="sc">+</span><span class="dv">22</span>,<span class="at">length.out=</span><span class="dv">100</span>)</span>
<span id="cb70-2"><a href="preliminaries.html#cb70-2" aria-hidden="true" tabindex="-1"></a>pdfs <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x, <span class="at">mean =</span> <span class="dv">1</span>, <span class="at">sd=</span><span class="dv">2</span>)</span>
<span id="cb70-3"><a href="preliminaries.html#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x,pdfs)</span></code></pre></div>
<p><img src="YA_TextBook_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>We assume that our <span class="math inline">\(x\)</span> is <span class="math inline">\(X \sim N\left(\mu = 1, \sigma^{2}=4\right)\)</span>. There are two assumption made here: (1) <span class="math inline">\(x\)</span> is normally distributed (as you can see from the code it’s a wrong assumption, but ignore it for now); (2) the distribution is defined by mean = 1 and sd = 2. The main goal in defining the likelihood function is to find the distribution parameters (mean and sd in a normal distribution) that fit to the observed data best.</p>
<p>Let’s have an example. Pretend that we do not see and know the following data creation:</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="preliminaries.html#cb71-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>, <span class="dv">2</span>, <span class="dv">7</span>)</span></code></pre></div>
<p>Of course we can plot the data and calculate the parameters of its distribution (the mean and standard deviation of <span class="math inline">\(x\)</span>). However, how can we do it with likelihood function?</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="preliminaries.html#cb72-1" aria-hidden="true" tabindex="-1"></a>pdfs1 <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x, <span class="at">mean =</span> <span class="dv">1</span>, <span class="at">sd=</span><span class="dv">2</span>)</span>
<span id="cb72-2"><a href="preliminaries.html#cb72-2" aria-hidden="true" tabindex="-1"></a>pdfs2 <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x, <span class="at">mean =</span> <span class="dv">5</span>, <span class="at">sd=</span><span class="dv">7</span>)</span>
<span id="cb72-3"><a href="preliminaries.html#cb72-3" aria-hidden="true" tabindex="-1"></a>pdfs3 <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x, <span class="at">mean =</span> <span class="dv">2</span>, <span class="at">sd=</span><span class="dv">7</span>)</span>
<span id="cb72-4"><a href="preliminaries.html#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</span>
<span id="cb72-5"><a href="preliminaries.html#cb72-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x,pdfs1)</span>
<span id="cb72-6"><a href="preliminaries.html#cb72-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x,pdfs2)</span>
<span id="cb72-7"><a href="preliminaries.html#cb72-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x,pdfs2)</span></code></pre></div>
<p><img src="YA_TextBook_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Which one is the best distribution, representing the true distribution of the data? This is the idea behind Maximum likelihood method. Let’s define the likelihood function for <span class="math inline">\(x\)</span>:</p>
<p>It seems reasonable that a good estimate of the unknown parameter <span class="math inline">\(\mu\)</span> would be the value of <span class="math inline">\(\mu\)</span> that maximizes the the likelihood (not the probability!) of getting the data we observed. The probability density (or mass) function of each <span class="math inline">\(x_{i}\)</span> is <span class="math inline">\(f\left(x_{i} ; \mu, \sigma^2\right)\)</span>. Then, the joint probability density function of <span class="math inline">\(x_{1}, x_{2}, \cdots, x_{n}\)</span>, which we’ll call <span class="math inline">\(L(\mu, \sigma^2)\)</span> is:</p>
<p><span class="math display">\[
L(\mu, \sigma^2)=P\left(X_{1}=x_{1}, X_{2}=x_{2}, \ldots, X_{n}=x_{n}\right)=f\left(x_{1} ; \mu,\sigma^2\right) \cdot f\left(x_{2} ; \mu,\sigma^2\right) \cdots f\left(x_{n} ; \mu, \sigma^2\right)=\prod_{i=1}^{n} f\left(x_{i} ; \mu, \sigma^2\right)
\]</span>
The first equality is just the definition of the joint probability density function. The second equality comes from that fact that we have a random sample, <span class="math inline">\(x_i\)</span>, that are independent
are independent. Hence, the likelihood function is:</p>
<p><span class="math display">\[
L(\mu, \sigma)=\sigma^{-n}(2 \pi)^{-n / 2} \exp \left[-\frac{1}{2 \sigma^{2}} \sum_{i=1}^{n}\left(x_{i}-\mu\right)^{2}\right]
\]</span></p>
<p>and therefore the log of the likelihood function:</p>
<p><span class="math display">\[
\log L\left(\mu, \theta_{2}\right)=-\frac{n}{2} \log \sigma^{2}-\frac{n}{2} \log (2 \pi)-\frac{\sum\left(x_{i}-\mu\right)^{2}}{2 \sigma^{2}}
\]</span>
Now, upon taking the partial derivative of the log likelihood with respect to <span class="math inline">\(\mu\)</span> and setting to 0, we see that:</p>
<p><span class="math display">\[
\frac{\partial \log L\left(\theta_{1}, \theta_{2}\right)}{\partial \theta_{1}}=\frac{-\not 2 \sum\left(x_{i}-\mu\right)(-\not1)}{\not2 \sigma^{2}} \stackrel{\mathrm{SET}}{=} 0
\]</span>
and we get</p>
<p><span class="math display">\[
\sum x_{i}-n \mu=0
\]</span>
<span class="math display">\[
\hat{\mu}=\frac{\sum x_{i}}{n}=\bar{x}
\]</span></p>
<p>We can solve for <span class="math inline">\(sigma^2\)</span> by the same way.</p>
<p>Now the regression. Since,</p>
<p><span class="math display">\[
Y_{i} | X_{i} \sim N\left(\beta_{0}+\beta_{1} x_{i}, \sigma^{2}\right)
\]</span></p>
<p><span class="math display">\[
f_{y_{i}}\left(y_{i} ; x_{i}, \beta_{0}, \beta_{1}, \sigma^{2}\right)=\frac{1}{\sqrt{2 \pi \sigma^{2}}} \exp \left[-\frac{1}{2}\left(\frac{y_{i}-\left(\beta_{0}+\beta_{1} x_{i}\right)}{\sigma}\right)^{2}\right]
\]</span></p>
<p>Given <span class="math inline">\(n\)</span> data points <span class="math inline">\((x_i,y_i)\)</span> we can write the likelihood as a function of the three parameters <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>, and <span class="math inline">\(\sigma^2\)</span>.</p>
<p><span class="math display" id="eq:2-9">\[\begin{equation}
L\left(\beta_{0}, \beta_{1}, \sigma^{2}\right)=\prod_{i=1}^{n} \frac{1}{\sqrt{2 \pi \sigma^{2}}} \exp \left[-\frac{1}{2}\left(\frac{y_{i}-\beta_{0}-\beta_{1} x_{i}}{\sigma}\right)^{2}\right]
  \tag{2.9}
\end{equation}\]</span></p>
<p>Our goal is to find values of <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>, and <span class="math inline">\(\sigma^2\)</span> which maximize Function 2.9. It is a straightforward multivariate calculus problem. First, let’s re-write 2.9 as follows:</p>
<p><span class="math display" id="eq:2-10">\[\begin{equation}
L\left(\beta_{0}, \beta_{1}, \sigma^{2}\right)=\left(\frac{1}{\sqrt{2 \pi \sigma^{2}}}\right)^{n} \exp \left[-\frac{1}{2 \sigma^{2}} \sum_{i=1}^{n}\left(y_{i}-\beta_{0}-\beta_{1} x_{i}\right)^{2}\right]
  \tag{2.10}
\end{equation}\]</span></p>
<p>We can make 2.10 linear by taking the log of this function, which is called as <strong>the log-likelihood function</strong>.</p>
<p><span class="math display" id="eq:2-11">\[\begin{equation}
\log L\left(\beta_{0}, \beta_{1}, \sigma^{2}\right)=-\frac{n}{2} \log (2 \pi)-\frac{n}{2} \log \left(\sigma^{2}\right)-\frac{1}{2 \sigma^{2}} \sum_{i=1}^{n}\left(y_{i}-\beta_{0}-\beta_{1} x_{i}\right)^{2}
  \tag{2.11}
\end{equation}\]</span></p>
<p>The rest would be simple calculus:</p>
<p><span class="math display">\[
\frac{\partial \log L(\beta_{0}, \beta_{1}, \sigma^{2})}{\partial \beta_{0}}=\frac{1}{\sigma^{2}} \sum_{i=1}^{n}\left(y_{i}-\beta_{0}-\beta_{1} x_{i}\right),
\]</span></p>
<p><span class="math display">\[
\frac{\partial \log L\left(\beta_{0}, \beta_{1}, \sigma^{2}\right)}{\partial \beta_{1}}=\frac{1}{\sigma^{2}} \sum_{i=1}^{n}\left(x_{i}\right)\left(y_{i}-\beta_{0}-\beta_{1} x_{i}\right),
\]</span></p>
<p>and,</p>
<p><span class="math display">\[
\frac{\partial \log L\left(\beta_{0}, \beta_{1}, \sigma^{2}\right)}{\partial \sigma^{2}}=-\frac{n}{2 \sigma^{2}}+\frac{1}{2\left(\sigma^{2}\right)^{2}} \sum_{i=1}^{n}\left(y_{i}-\beta_{0}-\beta_{1} x_{i}\right)^{2}
\]</span></p>
<p>These first order conditions yield the following three equations with three unknown parameters:</p>
<p><span class="math display">\[
\begin{aligned} \sum_{i=1}^{n}\left(y_{i}-\beta_{0}-\beta_{1} x_{i}\right) &amp;=0 \\ \sum_{i=1}^{n}\left(x_{i}\right)\left(y_{i}-\beta_{0}-\beta_{1} x_{i}\right) &amp;=0 \\-\frac{n}{2 \sigma^{2}}+\frac{1}{2\left(\sigma^{2}\right)^{2}} \sum_{i=1}^{n}\left(y_{i}-\beta_{0}-\beta_{1} x_{i}\right)^{2} &amp;=0 \end{aligned}
\]</span></p>
<p>We call these estimates the maximum likelihood estimates. They are exactly the same as OLS parameters, except for the variance.</p>
<p>So we now have two different estimates of <span class="math inline">\(\sigma^{2}\)</span>.</p>
<p><span class="math display">\[
\begin{aligned} s_{e}^{2} &amp;=\frac{1}{n-2} \sum_{i=1}^{n}\left(y_{i}-\hat{y}_{i}\right)^{2}=\frac{1}{n-2} \sum_{i=1}^{n} e_{i}^{2} \quad \text { Least Squares } \end{aligned}
\]</span></p>
<p><span class="math display">\[
\begin{aligned}  \hat{\sigma}^{2} &amp;=\frac{1}{n} \sum_{i=1}^{n}\left(y_{i}-\hat{y}_{i}\right)^{2}=\frac{1}{n} \sum_{i=1}^{n} e_{i}^{2} \quad \text {MLE}\end{aligned}
\]</span></p>
</div>
<div id="estimating-mle-with-r" class="section level3 hasAnchor" number="2.4.3">
<h3><span class="header-section-number">2.4.3</span> Estimating MLE with R<a href="preliminaries.html#estimating-mle-with-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>How can we make estimations with MLE? It is good to look at a simple example. Suppose the observations <span class="math inline">\(X_1,X_2,...,X_n\)</span> are from <span class="math inline">\(N(\mu,\sigma^{2})\)</span> distribution (2 parameters: the mean and the variance). The likelihood function is:</p>
<p><span class="math display" id="eq:2-12">\[\begin{equation}
L(x)=\prod_{i=1}^{i=n} \frac{1}{\sqrt{2 \pi \sigma^{2}}} e^{-\frac{(x-\mu)^{2}}{2 \sigma^{2}}}
  \tag{2.12}
\end{equation}\]</span></p>
<p>The objective is to find out the mean and the variance of the sample. Of course this a silly example: instead of using MLE to calculate them, we can use our middle-school algebra and find them right away. But the point here is to show how MLE works. And more importantly, we now have a different way to estimate the mean and the variance. The question here is, <strong>given the data, what parameters (mean and variance) would give us the maximum joint density</strong>. Hence, <strong>the likelihood function is a function of the parameter only, with the data held as a fixed constant</strong>, which gives us an idea of how well the data summarizes these parameters. Because we are interested in observing all the data points jointly, it can be calculated as a product of marginal densities of each observation assuming that observations are independent and identically distributed.</p>
<p>Here is an example:</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="preliminaries.html#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Let&#39;s create a sample of normal variables</span></span>
<span id="cb73-2"><a href="preliminaries.html#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2019</span>)</span>
<span id="cb73-3"><a href="preliminaries.html#cb73-3" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>)</span>
<span id="cb73-4"><a href="preliminaries.html#cb73-4" aria-hidden="true" tabindex="-1"></a><span class="co"># And the likelihood fo these x&#39;s is</span></span>
<span id="cb73-5"><a href="preliminaries.html#cb73-5" aria-hidden="true" tabindex="-1"></a><span class="fu">prod</span>(<span class="fu">dnorm</span>(x))</span></code></pre></div>
<pre><code>## [1] 2.23626e-58</code></pre>
<p>What’s happening here? One issue with the MLE method is that, as probability densities are often smaller than 1, the value of <span class="math inline">\(L(x)\)</span> would be very small. Or very high, if the variance is very high. This could be a worse problem for large samples and create a problem for computers in terms of storage and precision. The solution would be the log-likelihood:</p>
<p><span class="math display" id="eq:2-13">\[\begin{equation}
\log (\mathcal{L}(\mu, \sigma))=-\frac{n}{2} \log \left(2 \pi \sigma^{2}\right)-\frac{1}{2 \sigma^{2}} \sum_{i=1}^{n}\left(x_{i}-\mu\right)^{2}
  \tag{2.13}
\end{equation}\]</span></p>
<p>In a more realistic case we can only observe a sample of some data points and <strong>assume</strong> how it is distributed. With this assumption we can have a log-likelihood function. Hence, if it’s a wrong assumption, our estimations will be wrong as well. The fact that we have to make assumptions about pdf’s will be very important issue when we cover nonparamateric estimations.</p>
<p>Let’s assume that we have 100 <span class="math inline">\(x\)</span>’s with <span class="math inline">\(x\sim N\left(\mu, \sigma^{2}\right)\)</span>. We can now compute the derivatives of this log-likelihood and calculate the parameters. However, instead of this manual analytic optimization procedure, we can use R packages or algorithmic/numerical optimization methods. In fact, except for trivial models, the analytic methods cannot be applied to solve for the parameters. R has two packages <code>optim()</code> and <code>nlm()</code> that use <strong>algorithmic optimization</strong> methods, which we will see in the this book as a separate chapter. For these optimization methods, it really does not matter how complex or simple the function is, as they will treat it as a black box.</p>
<p>Here we can re-write function 2.13 :</p>
<p><span class="math display" id="eq:2-14">\[\begin{equation}
-\sum\left(\frac{\left(x_{i}-\mu\right)^{2}}{2 \sigma^{2}}+1 / 2 \log 2 \pi+1 / 2 \log \sigma^{2}\right),
  \tag{2.14}
\end{equation}\]</span></p>
<p>Instead of finding the parameters that minimize this <strong>negative</strong> function, we can find the maximum of the negative of this function. We can omit the term <span class="math inline">\(-1/2\log2\pi\)</span> and define the function to R as follows:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="preliminaries.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Here is our function f(x)</span></span>
<span id="cb75-2"><a href="preliminaries.html#cb75-2" aria-hidden="true" tabindex="-1"></a>fn <span class="ot">&lt;-</span> <span class="cf">function</span>(prmt){</span>
<span id="cb75-3"><a href="preliminaries.html#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fl">0.5</span><span class="sc">*</span>(x <span class="sc">-</span> prmt[<span class="dv">1</span>])<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>prmt[<span class="dv">2</span>] <span class="sc">+</span> <span class="fl">0.5</span><span class="sc">*</span><span class="fu">log</span>(prmt[<span class="dv">2</span>]))</span>
<span id="cb75-4"><a href="preliminaries.html#cb75-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb75-5"><a href="preliminaries.html#cb75-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-6"><a href="preliminaries.html#cb75-6" aria-hidden="true" tabindex="-1"></a><span class="co">#We have two packages nlm() and optim() to solve it</span></span>
<span id="cb75-7"><a href="preliminaries.html#cb75-7" aria-hidden="true" tabindex="-1"></a><span class="co">#We arbitrarily pick starting points for the parameters</span></span>
<span id="cb75-8"><a href="preliminaries.html#cb75-8" aria-hidden="true" tabindex="-1"></a>sol1 <span class="ot">&lt;-</span> <span class="fu">nlm</span>(fn, prmt <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">hessian=</span><span class="cn">TRUE</span>)</span>
<span id="cb75-9"><a href="preliminaries.html#cb75-9" aria-hidden="true" tabindex="-1"></a>sol2 <span class="ot">&lt;-</span> <span class="fu">optim</span>(prmt <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), fn, <span class="at">hessian=</span><span class="cn">TRUE</span>)</span>
<span id="cb75-10"><a href="preliminaries.html#cb75-10" aria-hidden="true" tabindex="-1"></a>sol1</span></code></pre></div>
<pre><code>## $minimum
## [1] 39.56555
## 
## $estimate
## [1] -0.07333445  0.81164723
## 
## $gradient
## [1] 5.478284e-06 4.384049e-06
## 
## $hessian
##               [,1]         [,2]
## [1,] 123.206236680 -0.007519674
## [2,]  -0.007519674 75.861573379
## 
## $code
## [1] 1
## 
## $iterations
## [1] 10</code></pre>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="preliminaries.html#cb77-1" aria-hidden="true" tabindex="-1"></a>sol2</span></code></pre></div>
<pre><code>## $par
## [1] -0.07328781  0.81161672
## 
## $value
## [1] 39.56555
## 
## $counts
## function gradient 
##       51       NA 
## 
## $convergence
## [1] 0
## 
## $message
## NULL
## 
## $hessian
##               [,1]         [,2]
## [1,] 123.210867601 -0.007012263
## [2,]  -0.007012263 75.911070194</code></pre>
<p>Let’s check if these estimates are correct:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="preliminaries.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co">#mean</span></span>
<span id="cb79-2"><a href="preliminaries.html#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x)</span></code></pre></div>
<pre><code>## [1] -0.073334</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="preliminaries.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co">#sd</span></span>
<span id="cb81-2"><a href="preliminaries.html#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>((x<span class="sc">-</span><span class="fu">mean</span>(x))<span class="sc">^</span><span class="dv">2</span> )<span class="sc">/</span><span class="fu">length</span>(x)</span></code></pre></div>
<pre><code>## [1] 0.8116477</code></pre>
<p>This is nice. But we need to know little bit more about how <code>optim()</code> and <code>nlp()</code> works. More specifically, what’s an algorithmic optimization? We leave it to <strong>Algorithmic Optimization</strong> in Appendix.</p>
</div>
</div>
<div id="blue" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> BLUE<a href="preliminaries.html#blue" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Statistical inference makes propositions about a population, using the sample data drawn from the population with some form of sampling. We use estimators on the sample to estimate the unknown population parameters. If we want to estimate the population mean of <span class="math inline">\(X\)</span>, <span class="math inline">\(\mu_X\)</span>, we use <span class="math inline">\(n^{-1}\Sigma x_i\)</span> as an estimator on the sample. The choice of <span class="math inline">\(n^{-1}\Sigma x_i\)</span> as an estimator seems commonsense, but why? What’s the criteria for a “good” estimator? The answer to this question is the key subject in econometrics and causal analysis. The requirement is that an estimator must be the best (B) linear (L) unbiased (U) estimator (E) of the population parameter for a proper statistical inference.</p>
<p>The Gauss–Markov theorem states that the <span class="math inline">\(\hat{\beta}_{0} \text { and } \hat{\beta}_{1}\)</span> in the sample regression function (<span class="math inline">\(Y_{i}=\hat{\beta}_{0}+\hat{\beta}_{1} x_{i}+\hat{\epsilon}_{i}\)</span>) are the best (B) linear (L) unbiased (U) estimators (E) of <span class="math inline">\(\beta_{0} \text { and } \beta_{1}\)</span> provided that certain assumptions on the population regression function (<span class="math inline">\(Y_{i}=\beta_{0}+\beta_{1} x_{i}+\epsilon_{i}\)</span>) are satisfied. We will now discuss U (unbiased) and B (best) as they relates to these estimators.</p>
<p>One measure of the “goodness” of an estimator is its unbiasedness, meaning that their expected value is the parameter being estimated. In the case of the regression estimates, we have:</p>
<p><span class="math display">\[
\begin{array}{l}{\mathrm{E}\left[\hat{\beta}_{0}\right]=\beta_{0}} \\ {\mathrm{E}\left[\hat{\beta}_{1}\right]=\beta_{1}}\end{array}
\]</span></p>
<p>Recall the sampling distribution you’ve learned in statistics. The idea is simple. You have a population, but its characteristics are unknown to us, usually because it is too large. However, we can use a random sample to estimate the parameters of interest for the population. This generalization from the sample to the population requires the concept of sampling distribution.</p>
<p>Suppose we want to estimate the average age of the local population. You calculate the average age as 23 from a sample of 200 people randomly selected from the population. But, if you keep sampling 1000 times (1000 samples, 200 people in each), each sample will give you a different estimate. Which one should be used for the generalization (population)? None of them. We know that the average of all average ages calculated from 1000 samples will be the most correct average of the population, although only if the estimator is unbiased. In a simple average, the proof is easy. We will review a simulation now, which you will learn later (Section 2.8).</p>
<p>In this exercise we will create our own sampling distribution for <span class="math inline">\(\bar{x}\)</span>. The population <span class="math inline">\(x\)</span> has the following probability distribution: <span class="math inline">\(N\left(0, \sigma^{2}\right)\)</span>. Pretend that we do not know this We will draw 1000 samples from this population. Each sample will have 200 <span class="math inline">\(x\)</span>’s. Thus, we will calculate 1000 <span class="math inline">\(\bar{x}\)</span>’s. The objective is to see if</p>
<p><span class="math display">\[
\mathbf E\left(\bar{x}\right)=\mu_x
\]</span></p>
<p>This is a simple exercise for R that we will learn in our lab sessions at the back of the book.</p>
<p>There are multiple ways to do this simulation.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="preliminaries.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># population (1 million x&#39;s)</span></span>
<span id="cb83-2"><a href="preliminaries.html#cb83-2" aria-hidden="true" tabindex="-1"></a>pop_x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1000000</span>, <span class="at">mean =</span> <span class="dv">5</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb83-3"><a href="preliminaries.html#cb83-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-4"><a href="preliminaries.html#cb83-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Random Sampling</span></span>
<span id="cb83-5"><a href="preliminaries.html#cb83-5" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">200</span> <span class="co"># number of x&#39;s in each sample</span></span>
<span id="cb83-6"><a href="preliminaries.html#cb83-6" aria-hidden="true" tabindex="-1"></a>mcn <span class="ot">&lt;-</span> <span class="dv">1000</span> <span class="co"># number of samples in the simulation</span></span>
<span id="cb83-7"><a href="preliminaries.html#cb83-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-8"><a href="preliminaries.html#cb83-8" aria-hidden="true" tabindex="-1"></a>samp <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, <span class="at">nrow =</span> n, <span class="at">ncol =</span> mcn) <span class="co"># a Container: matrix by 200 x 1000</span></span>
<span id="cb83-9"><a href="preliminaries.html#cb83-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span> mcn){</span>
<span id="cb83-10"><a href="preliminaries.html#cb83-10" aria-hidden="true" tabindex="-1"></a>  samp[,i] <span class="ot">&lt;-</span> <span class="fu">sample</span>(pop_x, n, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb83-11"><a href="preliminaries.html#cb83-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb83-12"><a href="preliminaries.html#cb83-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-13"><a href="preliminaries.html#cb83-13" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(samp) <span class="co"># We calculate the column means</span></span>
<span id="cb83-14"><a href="preliminaries.html#cb83-14" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">mean</span>(xbar) <span class="co"># the mean of xbars</span></span>
<span id="cb83-15"><a href="preliminaries.html#cb83-15" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(mu, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 5</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="preliminaries.html#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(xbar, <span class="at">breaks=</span><span class="dv">20</span>)</span></code></pre></div>
<p><img src="YA_TextBook_files/figure-html/MC2-1.png" width="672" /></p>
<p>As we see, our estimator, <span class="math inline">\(\sum_{i=1}^{n}\left(x_{i}\right)/n\)</span>, is an unbiased estimator of the population mean. But is that enough?</p>
<p>Now, if we are happy with our unbiased estimator, how do we choose one estimator among all other unbiased estimators? How do we define the best estimator? The answer is simple: we choose the one with the minimum sampling variance. Why do we need the minimum variance? Remember more variance means higher differences in <span class="math inline">\(\hat{\beta}_{0} \text { and } \hat{\beta}_{1}\)</span> from sample to sample. That means a very large confidence interval for the <span class="math inline">\(\mu_x\)</span>. Since we have only one sample in practice, the high sampling variance results in greater likelihood that we will get results further away from the <strong>mean</strong> of <span class="math inline">\(\bar{x}\)</span>, which is captured by the confidence interval.</p>
<p>First, note that it is very easy to create an estimator for <span class="math inline">\(\beta_{1}\)</span> that has very low variance, but is not unbiased. For example, define <span class="math inline">\(\hat{\theta}_{B A D}=5\)</span>. Since <span class="math inline">\(\hat{\theta}_{B A D}\)</span> is constant,</p>
<p><span class="math display">\[
\begin{array}{r}{\mathbf{Var}\left[\hat{\theta}_{B A D}\right]=0} \end{array}
\]</span></p>
<p>However since, <span class="math inline">\(\mathbf{E}\left[\hat{\theta}_{B A D}\right]=5\)</span>, we can say that <span class="math inline">\(\hat{\theta}_{B A D}\)</span> is not a good estimator even though it has the smallest possible variance. Hence two conditions, unbiasedness and minimum variance, have an order: we look for an estimator with the minimum variance in unbiased estimators.</p>
<p><strong>Omitted Variable Bias (OVB)</strong></p>
<p>One of the main reasons for a biased estimator in regression models is that the estimated model may “omit” some necessary variables. Here is a more realistic example from Stock and Watson (2015, p. 196): Suppose we want to make an analysis of the relationship between test score and class size. If we run this regression, we may face a major flaw: we ignore other determinants of the dependent variable (test score) that correlate with the regressor (class size). Remember that influences on the dependent variable which are not captured by the model are collected in the error term. As long as these omitted variables are correlated with the regressors (<span class="math inline">\(x\)</span>) in the model, the conditional expectation on the error term becomes non-zero, <span class="math inline">\(\text{E}(\epsilon|x)\neq0\)</span>. This leads to an estimation bias, i.e., the mean of the OLS estimator’s sampling distribution is no longer equals the true mean. This issue is called omitted variable bias (OVB).</p>
<p>In the example of test score and class size, it is easy to come up with variables that may cause such a bias, if omitted from the model. In our case, a highly relevant variable could be the percentage of English learners in the school district: it is plausible that the ability to speak, read and write English is an important factor for successful learning. Therefore, students that are still learning English are likely to perform worse in tests than native speakers. Also, it is conceivable that the share of English learning students is bigger in school districts where class sizes are relatively large: think of poor urban districts where a lot of immigrants live. Hence the “true” model should look like equation 2.15:</p>
<p><span class="math display" id="eq:2-15">\[\begin{equation}
Test Score =\beta_{0}+\beta_{1}S T R+\beta_{2}PctEL+\epsilon_{i},
  \tag{2.15}
\end{equation}\]</span></p>
<p>where <em>STR</em> and <em>PctEL</em> are correlated, that is <span class="math inline">\(\rho_{str,~ pctel} \neq 0\)</span>.</p>
<p>We can omit <em>PctEL</em> in 2.15 and estimate it as</p>
<p><span class="math display" id="eq:2-16">\[\begin{equation}
Test Score =\hat{\beta}_{0}+\hat{\beta}_{1}STR+v_{i}.
  \tag{2.16}
\end{equation}\]</span></p>
<p>Intuitively, as the omitted variable, PctEL, joins to the residual (<span class="math inline">\(v_i\)</span>), <span class="math inline">\(\hat{\beta}_{1}\)</span> will not reflect the true effect of changes in STR on the test score. We can formally see the result of this omission as follows:</p>
<p><span class="math display">\[
\hat{\beta}_{1}=\frac{\mathbf{Cov}\left(STR_{i},TestScore_{i}\right)}{\mathbf{Var}\left(STR_{i}\right)}=\frac{\sum_{i}\left(x_{i}-\bar{x}\right)\left(y_{i}-\bar{y}\right)}{\sum_{i}\left(x_{i}-\bar{x}\right)^{2}}=\frac{\sum_{i}\left(x_{i}-\bar{x}\right) y_{i}}{\sum_{i}\left(x_{i}-\bar{x}\right) x_{i}}
\]</span></p>
<p>We can substitute <span class="math inline">\(y_i\)</span> into the last term and simplify:</p>
<p><span class="math display">\[
\begin{aligned} \hat{\beta}_{1} &amp;=\frac{\sum_{i}\left(x_{i}-\bar{x}\right)\left(\beta_{0}+\beta_{1} x_{i}+\beta_{2} z_{i}+\epsilon_{i}\right)}{\sum_{i}\left(x_{i}-\bar{x}\right) x_{i}} =\beta_{1}+\beta_{2} \frac{\sum_{i}\left(x_{i}-\bar{x}\right) z_{i}}{\sum_{i}\left(x_{i}-\bar{x}\right) x_{i}}+\frac{\sum_{i}\left(x_{i}-\bar{x}\right) \epsilon_{i}}{\sum_{i}\left(x_{i}-\bar{x}\right) x_{i}}, \end{aligned}
\]</span></p>
<p>where <span class="math inline">\(z\)</span> is <span class="math inline">\(PctEL\)</span> (omitted variable), <span class="math inline">\(x\)</span> is <span class="math inline">\(STR\)</span>, <span class="math inline">\(y\)</span> is <span class="math inline">\(TestScore\)</span>. The second term is a result of our omission of variable <em>PctEL</em> (<span class="math inline">\(z\)</span>). If we take the expectation of the last line:</p>
<p><span class="math display">\[
\begin{aligned} \mathbf{E}\left[\hat{\beta}_{1}\right] &amp;=\mathbf{E}\left[\beta_{1}+\beta_{2} \frac{\sum_{i}\left(x_{i}-\bar{x}\right) z_{i}}{\sum_{i}\left(x_{i}-\bar{x}\right) x_{i}}+\frac{\sum_{i}\left(x_{i}-\bar{x}\right) \epsilon_{i}}{\sum_{i}\left(x_{i}-\bar{x}\right) x_{i}}\right] \\ &amp;=\beta_{1}+\beta_{2} \mathbf{E}\left[\frac{\sum_{i}\left(x_{i}-\bar{x}\right) z_{i}}{\sum_{i}\left(x_{i}-\bar{x}\right) x_{i}}\right]+\mathbf{E}\left[\frac{\sum_{i}\left(x_{i}-\bar{x}\right) \epsilon_{i}}{\sum_{i}\left(x_{i}-\bar{x}\right) x_{i}}\right] \\ &amp;=\beta_{1}+\beta_{2} [\text{cov}(x,z)/\text{var}(x)] \end{aligned}
\]</span></p>
<p>What this means is that on average, our regression estimate is going to miss the true population parameter by the second term. Here is the OVB in action:</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="preliminaries.html#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the AER package</span></span>
<span id="cb86-2"><a href="preliminaries.html#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AER)</span>
<span id="cb86-3"><a href="preliminaries.html#cb86-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-4"><a href="preliminaries.html#cb86-4" aria-hidden="true" tabindex="-1"></a><span class="co"># load the data set</span></span>
<span id="cb86-5"><a href="preliminaries.html#cb86-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(CASchools)</span>
<span id="cb86-6"><a href="preliminaries.html#cb86-6" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(CASchools)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    420 obs. of  14 variables:
##  $ district   : chr  &quot;75119&quot; &quot;61499&quot; &quot;61549&quot; &quot;61457&quot; ...
##  $ school     : chr  &quot;Sunol Glen Unified&quot; &quot;Manzanita Elementary&quot; &quot;Thermalito Union Elementary&quot; &quot;Golden Feather Union Elementary&quot; ...
##  $ county     : Factor w/ 45 levels &quot;Alameda&quot;,&quot;Butte&quot;,..: 1 2 2 2 2 6 29 11 6 25 ...
##  $ grades     : Factor w/ 2 levels &quot;KK-06&quot;,&quot;KK-08&quot;: 2 2 2 2 2 2 2 2 2 1 ...
##  $ students   : num  195 240 1550 243 1335 ...
##  $ teachers   : num  10.9 11.1 82.9 14 71.5 ...
##  $ calworks   : num  0.51 15.42 55.03 36.48 33.11 ...
##  $ lunch      : num  2.04 47.92 76.32 77.05 78.43 ...
##  $ computer   : num  67 101 169 85 171 25 28 66 35 0 ...
##  $ expenditure: num  6385 5099 5502 7102 5236 ...
##  $ income     : num  22.69 9.82 8.98 8.98 9.08 ...
##  $ english    : num  0 4.58 30 0 13.86 ...
##  $ read       : num  692 660 636 652 642 ...
##  $ math       : num  690 662 651 644 640 ...</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="preliminaries.html#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define variables</span></span>
<span id="cb88-2"><a href="preliminaries.html#cb88-2" aria-hidden="true" tabindex="-1"></a>CASchools<span class="sc">$</span>STR <span class="ot">&lt;-</span> CASchools<span class="sc">$</span>students<span class="sc">/</span>CASchools<span class="sc">$</span>teachers       </span>
<span id="cb88-3"><a href="preliminaries.html#cb88-3" aria-hidden="true" tabindex="-1"></a>CASchools<span class="sc">$</span>score <span class="ot">&lt;-</span> (CASchools<span class="sc">$</span>read <span class="sc">+</span> CASchools<span class="sc">$</span>math)<span class="sc">/</span><span class="dv">2</span></span></code></pre></div>
<p>Let us estimate both regression models and compare. Performing a multiple regression in R is straightforward. One can simply add additional variables to the right hand side of the formula argument of the function lm() by using their names and the + operator.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="preliminaries.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># estimate both regressions</span></span>
<span id="cb89-2"><a href="preliminaries.html#cb89-2" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> STR, <span class="at">data =</span> CASchools) <span class="co"># Underfitted model</span></span>
<span id="cb89-3"><a href="preliminaries.html#cb89-3" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> STR <span class="sc">+</span> english, <span class="at">data =</span> CASchools) <span class="co"># True model</span></span>
<span id="cb89-4"><a href="preliminaries.html#cb89-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-5"><a href="preliminaries.html#cb89-5" aria-hidden="true" tabindex="-1"></a>model1</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = score ~ STR, data = CASchools)
## 
## Coefficients:
## (Intercept)          STR  
##      698.93        -2.28</code></pre>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="preliminaries.html#cb91-1" aria-hidden="true" tabindex="-1"></a>model2</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = score ~ STR + english, data = CASchools)
## 
## Coefficients:
## (Intercept)          STR      english  
##    686.0322      -1.1013      -0.6498</code></pre>
<p>Is the magnitude of the bias, <span class="math inline">\(-1.1787 = -2.28 - (-1.1013)\)</span>, consistent with the formula, <span class="math inline">\(\beta_{2} [\text{cov}(x,z)/\text{var}(x)]\)</span>?</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="preliminaries.html#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cov</span>(CASchools<span class="sc">$</span>STR, CASchools<span class="sc">$</span>english)<span class="sc">/</span><span class="fu">var</span>(CASchools<span class="sc">$</span>STR)<span class="sc">*</span>model2<span class="sc">$</span>coefficients[<span class="dv">3</span>]</span></code></pre></div>
<pre><code>##   english 
## -1.178512</code></pre>
</div>
<div id="modeling-the-data" class="section level2 hasAnchor" number="2.6">
<h2><span class="header-section-number">2.6</span> Modeling the data<a href="preliminaries.html#modeling-the-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When modeling data, there are a number of choices that need to be made.</p>
<p>What <strong>family</strong> of models will be considered? In linear regression, we specified models with parameters (<span class="math inline">\(\beta{j}\)</span>) and fit the model by finding the best values of these parameters. This is a <em>parametric</em> approach. A <em>non-parametric</em> approach skips the step of specifying a model with parameters and are often described as more of an algorithm. Non-parametric models are often used in machine learning, which we will see in Part 2.</p>
<p>If we define a parametric model, what <strong>form</strong> of the model will be used for <span class="math inline">\(f(.)\)</span> shown below?</p>
<p><span class="math display">\[
y =f\left(x_{1}, x_{2}, x_{3}, \ldots, x_{p}\right)+\epsilon
\]</span>
Would it be linear or polynomial? If we are going to add non-linear terms, which variables would be selected with what degree of polynomial terms? Moreover, if there is no interaction between the predictors, one variable affects the response is the same for any values of the other predictors. Hence, we need to assume what the “true” population model (DGM) would be when searching for a model.</p>
<p>How will the model be <strong>fit</strong>? Although we have seen two of the most common techniques, OLS and MLE, there are more techniques in the literature.</p>
<p>Addressing these three questions are the fundamental steps in defining the relationships between variables and could be different in causal and predictive analyses.</p>
</div>
<div id="causal-vs.-predictive-models" class="section level2 hasAnchor" number="2.7">
<h2><span class="header-section-number">2.7</span> Causal vs. Predictive Models<a href="preliminaries.html#causal-vs.-predictive-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>What is the purpose of fitting a model to data? Usually it is to accomplish one of two goals. We can use a model to <strong>explain</strong> the causal relationship between the response and the explanatory variables. Models can also be used to <strong>predict</strong> the response based on the predictors.</p>
<div id="causal-models" class="section level3 hasAnchor" number="2.7.1">
<h3><span class="header-section-number">2.7.1</span> Causal Models<a href="preliminaries.html#causal-models" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If the goal of a model is to explain the causal relationship between the response and one or more of the explanatory variables, we are looking for a model that is <strong>small and interpretable</strong>, but still fits the data well.</p>
<p>Suppose we would like to identify the factors that explain fuel efficiency (mpg - miles per galon) based on a car’s attributes (<code>weight</code>, <code>year</code>, <code>hp</code>, etc.). If you are a car manufacturer trying to engineer a fuel efficient vehicle, you would like to know both which variables are useful for explaining mpg and how those variables affect fuel efficiency. Don’t forget: you are interested in a <strong>small and interpretable</strong> model.</p>
<p>Note that linear models of any size are rather interpretable to begin with. Later, we will see more complicated models that may fit data better, but are much harder, if not impossible to interpret. Because of this, these models aren’t nearly as useful for explaining a relationship. This is another reason to always attempt a linear model.</p>
<p>To find small and interpretable models, we use <strong>inferential</strong> techniques with additional assumptions about the error terms in a model:</p>
<p><span class="math display">\[
\epsilon \sim N\left(0, \sigma^{2}\right)
\]</span></p>
<p>This assumption states that the the error is normally distributed with some common variance. Also, this assumption states that the expected value of the error term is zero. This means that we should not have any OVB which, as we seen before, makes the expected error different than zero. In order words, the model has to be correctly specified without any omitted variable. These are the key to all of the inference we can make from a regression analysis.</p>
<p>One very important issue to understand a causal relationship is to distinguish two terms often used to describe a relationship between two variables: <strong>causation</strong> and <strong>correlation</strong>, both of which <strong>explain</strong> the relationship between <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span>.</p>
<p>Correlation is often also referred to as association. One good example is the empirical relationship between ice cream sales and the crime rate in a given region. <a href="https://en.wikipedia.org/wiki/The_Book_of_Why">It has been shown that</a> <span class="citation">(<a href="#ref-Pearl_Mackenzie_2018" role="doc-biblioref">Pearl and Mackenzie 2018</a>)</span> the correlation between these two measures are strong and positive. Just because these two variables are correlated does not necessarily mean that one causes the other (as people eat more ice cream, they commit more crime?). Perhaps there is a third variable that explains both! And it is known that very hot weather is that third missing factor that causes both ice cream sales and crime rates to go up. You can see many more absurd examples on the <a href="http://tylervigen.com/spurious-correlations">Spurious Correlations website</a>.</p>
<p>Causation is distinct from correlation, because it reflects a relationship in which one variable directly effects another. Rather than just an association between variables that may be caused by a third hidden variable, causation implies a direct link between the two. Continuing the example from earlier, the very hot weather has a causal connection with both ice cream sales and crime, even though those two outcomes only share a correlation with each other.</p>
</div>
<div id="prediction-models" class="section level3 hasAnchor" number="2.7.2">
<h3><span class="header-section-number">2.7.2</span> Prediction Models<a href="preliminaries.html#prediction-models" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If the goal of a model is to predict the response, then the only consideration is how well the model fits the data. Hence we do not need to have distributional assumptions as stated above. More specifically, correlation and causation are not an issue here. If a predictor is correlated with the response, it would be useful for prediction. For example, in elementary school aged children their shoe size certainly doesn’t <strong>cause</strong> them to read at a higher level, however we could very easily use shoe size to make a prediction about a child’s reading ability. The larger their shoe size, the better they read because their shoe size reflects their age!</p>
<p>However, as we see later, a word of caution is needed when using a model to predict an outcome. Mud on the ground would predict that we had a rain. Or if a person has been hospitalized for the last 3 months, we can predict that the person was sick. These types of predictions are useless and called usually <strong>model or data leaking</strong> in machine learning.</p>
<p><strong>What happens if we use a model built for causal analysis to predict the outcome?</strong> We will answer this question later. Keep this question in mind, because it will be a fundamental question to understand how machine learning or statistical learning would be different than a model that seeks a causation between <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span>.</p>
<p>Since we are not performing inference, life is relatively easier with predictive models. Therefore, the extra assumptions about the errors are not needed. The only thing we must care about is how close the predicted outcomes are to the observed outcomes. Your results might be largely uninterpretable and useless for inference, but for prediction none of that matters. For a specified model, it will find the values of the parameters which will <strong>minimize the squared prediction error</strong>, which is most often is the following root-mean-squared-error:</p>
<p><span class="math display">\[
\text { RMSPE }=\sqrt{\frac{1}{n} \sum_{i=1}^{n}\left(y_{i}-\hat{y}_{i}\right)^{2}},
\]</span></p>
<p>where <span class="math inline">\(y_i\)</span> are the actual values of the response for the “given data” and <span class="math inline">\(\hat{y}\)</span> are the predicted values using the fitted model and the predictors from the data. While the choice between <strong>RMSPE and MSPE</strong> is arbitrary, RMSPE has the same unit as the response variable. Later, we will see more performance metrics in addition to MSPE.</p>
<p>An important issue in calculating MSPE is which <span class="math inline">\(y\)</span>’s are supposed to be predicted. If we use the “same” <span class="math inline">\(y\)</span>’s that we also use to calculate <span class="math inline">\(\hat{y}\)</span>’s, MSPE will tend to be lower for a larger and more complex models. Since we use a sample, when we use a larger and the most complex model possible, the model will fit and predict that sample very well. However, it faces the “winner’s curse”: the model becomes too specific for that sample as it gets more complex. This is called <strong>overfitting</strong>.</p>
<p>When the model overfits, it will be less “generalizable” for another sample. Consequently, these overly specific models would have very poor predictions for “out-of-sample” data. This topic will be covered in the next section. But before that, lets have an example that shows an overfitting model:</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="preliminaries.html#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simple OLS</span></span>
<span id="cb95-2"><a href="preliminaries.html#cb95-2" aria-hidden="true" tabindex="-1"></a>model_ols <span class="ot">&lt;-</span> <span class="fu">lm</span>(dist <span class="sc">~</span> speed, <span class="at">data =</span> carsDF)</span>
<span id="cb95-3"><a href="preliminaries.html#cb95-3" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">coef</span>(model_ols)</span>
<span id="cb95-4"><a href="preliminaries.html#cb95-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-5"><a href="preliminaries.html#cb95-5" aria-hidden="true" tabindex="-1"></a><span class="co"># A complex model</span></span>
<span id="cb95-6"><a href="preliminaries.html#cb95-6" aria-hidden="true" tabindex="-1"></a>model_cmpx <span class="ot">&lt;-</span> <span class="fu">smooth.spline</span>(carsDF<span class="sc">$</span>speed, carsDF<span class="sc">$</span>dist, <span class="at">df=</span><span class="dv">19</span>)</span>
<span id="cb95-7"><a href="preliminaries.html#cb95-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-8"><a href="preliminaries.html#cb95-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(carsDF, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">pch =</span> <span class="dv">20</span>)</span>
<span id="cb95-9"><a href="preliminaries.html#cb95-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(b, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="dv">5</span>)</span>
<span id="cb95-10"><a href="preliminaries.html#cb95-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(model_cmpx,<span class="at">col=</span><span class="st">&#39;green&#39;</span>, <span class="at">lwd=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="YA_TextBook_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Let’s call two types of sample: <em>seen</em> (in-sample) and <em>unseen</em> (out-of-sample) data. The figure above shows two models fitted by using “seen” data, the data that we have on hand. In terms of fitting the model (minimizing MSPE), the “complex” (non-linear with green line) model is the best. The red dashed line is representing a simple linear model. If you use the “seen” data (sample you have) and the OLS criteria (minimizing MSE), the “complex” model should be chosen as a better model as it has the smallest MSPE.</p>
<p>But if we use these two models on “unseen” (out-of-sample) data to calculate MSE, which one will give us the minimum MSPE?</p>
<p>Suppose that you have two samples with the same variables. You give me the first sample and I don’t even know the existence of the second sample. You ask me to fit the model using the data you gave me. I did it by the rule of minimizing the RMSPE (or MSPE). And the complex model is the winner as it has the lower RMSPE. Now you gave me the second sample that I haven’t seen before. You then ask me to calculate RMSPE on this unseen data. Suppose I did. Would it be possible to have the following results (consider only the order of the numbers)?</p>
<table>
<thead>
<tr class="header">
<th align="center">Type of Model</th>
<th align="center">In-Sample RMSPE</th>
<th align="center">Out-Sample RMSPE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Simple model</td>
<td align="center">1.71</td>
<td align="center">1.45</td>
</tr>
<tr class="even">
<td align="center">Complex model</td>
<td align="center">1.41</td>
<td align="center">2.07</td>
</tr>
</tbody>
</table>
<p>We will answer it in coming chapters in details but, for now, let use our first simulation exercise.</p>
</div>
</div>
<div id="simulation" class="section level2 hasAnchor" number="2.8">
<h2><span class="header-section-number">2.8</span> Simulation<a href="preliminaries.html#simulation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Simulations are tools to see whether statistical arguments are true or not. In simulations, the data generating process (DGP) is known. We will know the form of the model as well as the value of each of the parameters. In particular, we will often control the distribution and parameters which define the randomness, or noise, in the data. One of the biggest strengths of R is its ability to carry out simulations using built-in functions for generating random samples from certain distributions. We’ll see many examples in the R labs (see Appendix).</p>
<p>Lets begin with an example. We are going to generate a sample of observations on <span class="math inline">\(Y\)</span> from a model (a.k.a. DGM):</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="preliminaries.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let create data</span></span>
<span id="cb96-2"><a href="preliminaries.html#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb96-3"><a href="preliminaries.html#cb96-3" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">20</span>, <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb96-4"><a href="preliminaries.html#cb96-4" aria-hidden="true" tabindex="-1"></a>dgm <span class="ot">&lt;-</span> <span class="dv">500</span> <span class="sc">+</span> <span class="dv">20</span><span class="sc">*</span>X <span class="sc">-</span> <span class="dv">90</span><span class="sc">*</span><span class="fu">sin</span>(X) <span class="co">#This is our DGM</span></span>
<span id="cb96-5"><a href="preliminaries.html#cb96-5" aria-hidden="true" tabindex="-1"></a>y <span class="ot">=</span> dgm <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="fu">length</span>(X), <span class="at">mean =</span> <span class="dv">10</span>, <span class="at">sd =</span> <span class="dv">100</span>) <span class="co">#This is our DGP</span></span>
<span id="cb96-6"><a href="preliminaries.html#cb96-6" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> <span class="fu">data.frame</span>(y,X)</span>
<span id="cb96-7"><a href="preliminaries.html#cb96-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-8"><a href="preliminaries.html#cb96-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X, y, <span class="at">col=</span><span class="st">&#39;deepskyblue4&#39;</span>,</span>
<span id="cb96-9"><a href="preliminaries.html#cb96-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&#39;X&#39;</span>, <span class="at">main=</span><span class="st">&#39;Observed data &amp; DGM&#39;</span>)</span>
<span id="cb96-10"><a href="preliminaries.html#cb96-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(X, dgm, <span class="at">col=</span><span class="st">&#39;firebrick1&#39;</span>, <span class="at">lwd=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="YA_TextBook_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>This is the plot of our simulated data. The simulated data points are the blue dots while the red line is the DGM or the systematic part. Now we have the data (<span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>) and we also know the underlying data generating procedure (DGP) that produces these observations. Let’s pretend that we do not know DGP. Our job is to estimate DGM. We will use three alternative models to estimate the true DGM.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="preliminaries.html#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># linear model</span></span>
<span id="cb97-2"><a href="preliminaries.html#cb97-2" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> X)</span>
<span id="cb97-3"><a href="preliminaries.html#cb97-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X, y, <span class="at">col=</span><span class="st">&#39;deepskyblue4&#39;</span>, <span class="at">xlab=</span><span class="st">&#39;X&#39;</span>, <span class="at">main=</span><span class="st">&#39;Linear&#39;</span>)</span>
<span id="cb97-4"><a href="preliminaries.html#cb97-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y <span class="sc">~</span> X, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>))</span></code></pre></div>
<p><img src="YA_TextBook_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="preliminaries.html#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Polynomial model (there is an easier way!)</span></span>
<span id="cb98-2"><a href="preliminaries.html#cb98-2" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> X <span class="sc">+</span> <span class="fu">I</span>(X<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(X<span class="sc">^</span><span class="dv">3</span>) <span class="sc">+</span> <span class="fu">I</span>(X<span class="sc">^</span><span class="dv">4</span>) <span class="sc">+</span>  <span class="fu">I</span>(X<span class="sc">^</span><span class="dv">5</span>) <span class="sc">+</span> <span class="fu">I</span>(X<span class="sc">^</span><span class="dv">6</span>) <span class="sc">+</span> <span class="fu">I</span>(X<span class="sc">^</span><span class="dv">7</span>) <span class="sc">+</span> <span class="fu">I</span>(X<span class="sc">^</span><span class="dv">8</span>)</span>
<span id="cb98-3"><a href="preliminaries.html#cb98-3" aria-hidden="true" tabindex="-1"></a>             <span class="sc">+</span> <span class="fu">I</span>(X<span class="sc">^</span><span class="dv">9</span>) <span class="sc">+</span> <span class="fu">I</span>(X<span class="sc">^</span><span class="dv">10</span>) <span class="sc">+</span> <span class="fu">I</span>(X<span class="sc">^</span><span class="dv">11</span>) <span class="sc">+</span> <span class="fu">I</span>(X<span class="sc">^</span><span class="dv">12</span>) <span class="sc">+</span> <span class="fu">I</span>(X<span class="sc">^</span><span class="dv">13</span>) <span class="sc">+</span> <span class="fu">I</span>(X<span class="sc">^</span><span class="dv">14</span>)</span>
<span id="cb98-4"><a href="preliminaries.html#cb98-4" aria-hidden="true" tabindex="-1"></a>             <span class="sc">+</span> <span class="fu">I</span>(X<span class="sc">^</span><span class="dv">15</span>) <span class="sc">+</span> <span class="fu">I</span>(X<span class="sc">^</span><span class="dv">16</span>) <span class="sc">+</span> <span class="fu">I</span>(X<span class="sc">^</span><span class="dv">17</span>) <span class="sc">+</span> <span class="fu">I</span>(X<span class="sc">^</span><span class="dv">18</span>), <span class="at">data=</span>data)</span>
<span id="cb98-5"><a href="preliminaries.html#cb98-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X, y, <span class="at">col=</span> <span class="st">&#39;deepskyblue4&#39;</span>, <span class="at">xlab=</span><span class="st">&#39;X&#39;</span>, <span class="at">main=</span><span class="st">&#39;Polynomial&#39;</span>)</span>
<span id="cb98-6"><a href="preliminaries.html#cb98-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(X, <span class="fu">fitted</span>(model2), <span class="at">col=</span><span class="st">&#39;firebrick1&#39;</span>, <span class="at">lwd=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="YA_TextBook_files/figure-html/unnamed-chunk-12-2.png" width="672" /></p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="preliminaries.html#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Nonparametric Model</span></span>
<span id="cb99-2"><a href="preliminaries.html#cb99-2" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">smooth.spline</span>(X,y,<span class="at">df=</span><span class="dv">200</span>)</span>
<span id="cb99-3"><a href="preliminaries.html#cb99-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X,y,<span class="at">col=</span><span class="st">&#39;deepskyblue4&#39;</span>,<span class="at">xlab=</span><span class="st">&#39;X&#39;</span>,<span class="at">main=</span><span class="st">&#39;Spline&#39;</span>)</span>
<span id="cb99-4"><a href="preliminaries.html#cb99-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(model3,<span class="at">col=</span><span class="st">&#39;firebrick1&#39;</span>, <span class="at">lwd=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="YA_TextBook_files/figure-html/unnamed-chunk-12-3.png" width="672" /></p>
<p>Which one do you think gives a better fit (the one with the smallest RMSPE)? I would pick the last one, the nonparametric spline model (we’ll see later what it is). Let’s calculate RMSPE for each.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="preliminaries.html#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let create a function for RMSPE</span></span>
<span id="cb100-2"><a href="preliminaries.html#cb100-2" aria-hidden="true" tabindex="-1"></a>rmse <span class="ot">=</span> <span class="cf">function</span>(actual, predicted) {</span>
<span id="cb100-3"><a href="preliminaries.html#cb100-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sqrt</span>(<span class="fu">mean</span>((actual <span class="sc">-</span> predicted) <span class="sc">^</span> <span class="dv">2</span>))</span>
<span id="cb100-4"><a href="preliminaries.html#cb100-4" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Now we have to keep <strong>predicted</strong> <span class="math inline">\(Y\)</span>’s in separate vectors for those 3 models:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="preliminaries.html#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicted values by the 3 models using the &quot;seen&quot; data</span></span>
<span id="cb101-2"><a href="preliminaries.html#cb101-2" aria-hidden="true" tabindex="-1"></a>predicted1<span class="ot">&lt;-</span> <span class="fu">fitted</span>(model1)</span>
<span id="cb101-3"><a href="preliminaries.html#cb101-3" aria-hidden="true" tabindex="-1"></a>predicted2<span class="ot">&lt;-</span> <span class="fu">fitted</span>(model2)</span>
<span id="cb101-4"><a href="preliminaries.html#cb101-4" aria-hidden="true" tabindex="-1"></a>predicted3<span class="ot">&lt;-</span> <span class="fu">predict</span>(model3, X)</span></code></pre></div>
<p>Now lets use our RMSPE function:</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="preliminaries.html#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co"># RMSPE&#39;s calculated using the &quot;seen&quot; data</span></span>
<span id="cb102-2"><a href="preliminaries.html#cb102-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Note that the actual y is the same for all models</span></span>
<span id="cb102-3"><a href="preliminaries.html#cb102-3" aria-hidden="true" tabindex="-1"></a>rmse1_s <span class="ot">&lt;-</span> <span class="fu">rmse</span>(predicted1, y)</span>
<span id="cb102-4"><a href="preliminaries.html#cb102-4" aria-hidden="true" tabindex="-1"></a>rmse2_s <span class="ot">&lt;-</span> <span class="fu">rmse</span>(predicted2, y)</span>
<span id="cb102-5"><a href="preliminaries.html#cb102-5" aria-hidden="true" tabindex="-1"></a>rmse3_s <span class="ot">&lt;-</span> <span class="fu">rmse</span>(predicted3<span class="sc">$</span>y, y)</span>
<span id="cb102-6"><a href="preliminaries.html#cb102-6" aria-hidden="true" tabindex="-1"></a>seen <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;RMSPE for model1 (linear)&quot;</span> <span class="ot">=</span> rmse1_s, <span class="st">&quot;RMSPE for model2 (polynomial)&quot;</span> <span class="ot">=</span> rmse2_s,</span>
<span id="cb102-7"><a href="preliminaries.html#cb102-7" aria-hidden="true" tabindex="-1"></a>          <span class="st">&quot;RMSPE for model3 (nonparametric)&quot;</span> <span class="ot">=</span> rmse3_s )</span>
<span id="cb102-8"><a href="preliminaries.html#cb102-8" aria-hidden="true" tabindex="-1"></a>seen</span></code></pre></div>
<pre><code>##        RMSPE for model1 (linear)    RMSPE for model2 (polynomial) 
##                        119.46405                         88.87396 
## RMSPE for model3 (nonparametric) 
##                         67.72450</code></pre>
<p>As expected, the the <span class="math inline">\(3^{rd}\)</span> model has the minimum RMSPE. Now we have another sample that we haven’t had before:</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="preliminaries.html#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Here is the &quot;unseen&quot; using the same X&#39;s as in the &quot;seen&quot; data.</span></span>
<span id="cb104-2"><a href="preliminaries.html#cb104-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-3"><a href="preliminaries.html#cb104-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2</span>)</span>
<span id="cb104-4"><a href="preliminaries.html#cb104-4" aria-hidden="true" tabindex="-1"></a><span class="co"># So the only difference is the random error</span></span>
<span id="cb104-5"><a href="preliminaries.html#cb104-5" aria-hidden="true" tabindex="-1"></a>y2 <span class="ot">=</span> dgm <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="fu">length</span>(X), <span class="at">mean =</span> <span class="dv">10</span>, <span class="at">sd =</span> <span class="dv">100</span>) </span>
<span id="cb104-6"><a href="preliminaries.html#cb104-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X, y2,<span class="at">col=</span><span class="st">&#39;deepskyblue4&#39;</span>,<span class="at">xlab=</span><span class="st">&#39;X&#39;</span>,<span class="at">main=</span><span class="st">&#39;The &quot;Unseen&quot; 2nd Sample&#39;</span>)</span></code></pre></div>
<p><img src="YA_TextBook_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="preliminaries.html#cb105-1" aria-hidden="true" tabindex="-1"></a>rmse1_us <span class="ot">&lt;-</span> <span class="fu">rmse</span>(predicted1, y2)</span>
<span id="cb105-2"><a href="preliminaries.html#cb105-2" aria-hidden="true" tabindex="-1"></a>rmse2_us<span class="ot">&lt;-</span> <span class="fu">rmse</span>(predicted2, y2)</span>
<span id="cb105-3"><a href="preliminaries.html#cb105-3" aria-hidden="true" tabindex="-1"></a>rmse3_us <span class="ot">&lt;-</span> <span class="fu">rmse</span>(predicted3<span class="sc">$</span>y, y2)</span>
<span id="cb105-4"><a href="preliminaries.html#cb105-4" aria-hidden="true" tabindex="-1"></a>unseen <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;RMSPE for model1 (linear)&quot;</span> <span class="ot">=</span> rmse1_us,</span>
<span id="cb105-5"><a href="preliminaries.html#cb105-5" aria-hidden="true" tabindex="-1"></a>            <span class="st">&quot;RMSPE for model2 (polynomial)&quot;</span> <span class="ot">=</span> rmse2_us,</span>
<span id="cb105-6"><a href="preliminaries.html#cb105-6" aria-hidden="true" tabindex="-1"></a>            <span class="st">&quot;RMSPE for model3 (nonparametric)&quot;</span> <span class="ot">=</span> rmse3_us)</span>
<span id="cb105-7"><a href="preliminaries.html#cb105-7" aria-hidden="true" tabindex="-1"></a>unseen</span></code></pre></div>
<pre><code>##        RMSPE for model1 (linear)    RMSPE for model2 (polynomial) 
##                         123.4378                         109.9968 
## RMSPE for model3 (nonparametric) 
##                         122.3018</code></pre>
<p>Let make a nice table:</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="preliminaries.html#cb107-1" aria-hidden="true" tabindex="-1"></a>table <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="dv">2</span>, <span class="dv">3</span>)</span>
<span id="cb107-2"><a href="preliminaries.html#cb107-2" aria-hidden="true" tabindex="-1"></a><span class="fu">row.names</span>(table) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Seen-data&quot;</span>, <span class="st">&quot;Unseen-data&quot;</span>)</span>
<span id="cb107-3"><a href="preliminaries.html#cb107-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(table) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Linear&quot;</span>, <span class="st">&quot;Polynomial&quot;</span>, <span class="st">&quot;Spline&quot;</span>)</span>
<span id="cb107-4"><a href="preliminaries.html#cb107-4" aria-hidden="true" tabindex="-1"></a>table[<span class="dv">1</span>,<span class="dv">1</span>] <span class="ot">&lt;-</span> seen[<span class="dv">1</span>]</span>
<span id="cb107-5"><a href="preliminaries.html#cb107-5" aria-hidden="true" tabindex="-1"></a>table[<span class="dv">1</span>,<span class="dv">2</span>] <span class="ot">&lt;-</span> seen[<span class="dv">2</span>]</span>
<span id="cb107-6"><a href="preliminaries.html#cb107-6" aria-hidden="true" tabindex="-1"></a>table[<span class="dv">1</span>,<span class="dv">3</span>] <span class="ot">&lt;-</span> seen[<span class="dv">3</span>]</span>
<span id="cb107-7"><a href="preliminaries.html#cb107-7" aria-hidden="true" tabindex="-1"></a>table[<span class="dv">2</span>,<span class="dv">1</span>] <span class="ot">&lt;-</span> unseen[<span class="dv">1</span>]</span>
<span id="cb107-8"><a href="preliminaries.html#cb107-8" aria-hidden="true" tabindex="-1"></a>table[<span class="dv">2</span>,<span class="dv">2</span>] <span class="ot">&lt;-</span> unseen[<span class="dv">2</span>]</span>
<span id="cb107-9"><a href="preliminaries.html#cb107-9" aria-hidden="true" tabindex="-1"></a>table[<span class="dv">2</span>,<span class="dv">3</span>] <span class="ot">&lt;-</span> unseen[<span class="dv">3</span>]</span>
<span id="cb107-10"><a href="preliminaries.html#cb107-10" aria-hidden="true" tabindex="-1"></a>table</span></code></pre></div>
<pre><code>##               Linear Polynomial   Spline
## Seen-data   119.4640   88.87396  67.7245
## Unseen-data 123.4378  109.99681 122.3018</code></pre>
<p>The last model estimated by spline has the minimum RMSPE using the seen data. It fits very well when we use the <strong>seen</strong> data but it is not so good at predicting the outcomes in the <strong>unseen</strong> data. Even if our objective is to understand the causal relationship between <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span> by using the <strong>seen</strong> data to find a model, spline and polynomial models contain large numbers of variables. Therefore, they are complex models and their interpretations are very difficult. Moreover, a better fitting model using only the <strong>seen</strong> data could be worse in prediction. This is called <strong>overfitting</strong>, which is what we will see in the next chapter.</p>

</div>
</div>



<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Pearl_Mackenzie_2018" class="csl-entry">
Pearl, Judea, and Dana Mackenzie. 2018. <em>The Book of Why</em>. 1st ed. Basic Books.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="learning-systems.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yaydede/ToolShed/edit/master/02-Preliminaries.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["YA_TextBook.pdf", "YA_TextBook.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
